### ISSUE TITLE
Error when there is no menu elements

### ISSUE THREAD

**Issue by scottwestover** [Vimux/Mainroad#100]
First, I just wanted to say thanks for this great theme. I recently started using this theme for my blog and when there are no menu items, I get the following error:

```
Uncaught Error: The nav element you are trying to select doesn't exist
```

<img width="1430" alt="screen shot 2018-10-27 at 10 44 23 pm" src="https://user-images.githubusercontent.com/9931822/47611355-e385fc00-da39-11e8-9f9d-3c5ed221f05d.png">

However, once I add at least one menu item the error goes away.

<img width="1429" alt="screen shot 2018-10-27 at 10 45 23 pm" src="https://user-images.githubusercontent.com/9931822/47611362-044e5180-da3a-11e8-8922-07fcdc1c988f.png">

I looked through the documentation, and I couldn't find anything mentioning how to disable the menu altogether.

Steps to recreate:
- create a new hugo site
- add the Mainroad theme and select it as your theme
- start the hugo server
- you should see the error when you view your site

Example repo with the issue:
https://github.com/scottwestover/hugo-theme-issue

**Comment by Vimux** [comment]
Hi @scottwestover. Thanks for the report.

Bug confirmed. He appeared in 08ff4c67f956cb435d2845177680caa2b0e4ab25 commit. I already working on fix.
