### ISSUE TITLE
nested menus

### ISSUE THREAD

**Issue by gstecca** [Vimux/Mainroad#101]
Does Mainroad support nested menus (submenus)? If yes can you please provide examples in the documentation? Is it possible to insert pages or sections as submenu entries?
If not can you suggest how to modify the theme to add them?

**Comment by Vimux** [comment]
Hi @gstecca.

No, Mainroad main menu doesn't support submenus. I do not plan to add this feature and I answered why in #86. I'm afraid if you want to add submenus, you should implement this feature by himself.

**Comment by gstecca** [comment]
Thanks @Vimux ! Just as an hint it would be nice to write in the readme that the theme does not support submenus (nested menus) and why. After read the #86 I agree with you. I will try to add some links to the md posts I wanted to do subsections.
Congratulations for the great work on Mainroad Hugo theme.

**Comment by Vimux** [comment]
> Just as an hint it would be nice to write in the readme that the theme does not support submenus (nested menus) and why. 

Thank you for suggestion. I will add a note, but without explaining any reasons. I think that will be enough.
