### ISSUE TITLE
featured image for posts

### ISSUE THREAD

**Issue by gstecca** [Vimux/Mainroad#102]
Dear Vimux,
 how to insert a featured image on posts?
Moreover, I do not know  how to correctly insert images on posts.
Hi have an img subfolder on the static folder.  But if I try to put something like:
!["the SIGMA Architecture"](/img/SIGMA-image.jpg)
i point to the root of the host and not on the root of my website. My website (under construction) is 
www.iasi.cnr.it/~stecca

Look for example to the image I tried to insert in the following post
http://www.iasi.cnr.it/~stecca/projects/2015sigma/

Thanks for help,
Giuseppe.

**Comment by gstecca** [comment]
Thanks Vimux.
The thumbnail is perfect, sorry I could not see because I used a different
theme before.

For inserting images inside posts my situation is bit different. In the
case of a post inside a folder (projects in my case) the link
(/img/yourimage.jpg) is not working.

I need to do (../../imgyourimage.jpg) in the case of the post in
http://www.website.org/~username/projects/2015sigma/
The baseurl will be something like http://www.website.org/~username/

There is any smarter solution?

Thanks again.
Giuseppe

**Comment by Vimux** [comment]
> I need to do (../../imgyourimage.jpg) in the case of the post in
http://www.website.org/~username/projects/2015sigma/
The baseurl will be something like http://www.website.org/~username/

I can advise you to read Hugo’s documentation about this. [Canonicalization](https://gohugo.io/content-management/urls/#canonicalization) and [Relative URLs](https://gohugo.io/content-management/urls/#relative-urls).

Try to change site settings:

```
CanonifyURLs = true
```

**Comment by gstecca** [comment]
Thanks Vimux,
 I solved everything.
Thank you again.
Giuseppe
