### ISSUE TITLE
Справка по компиляции

### ISSUE THREAD

**Issue by it-spectre-ru** [Vimux/Mainroad#105]
Здорово, потрясающе выглядит. Подскажите как скомпилировать данный шаблон и запустить, на локально веб сервере?

**Comment by Vimux** [comment]
Hello,

First of all, you need to [install Hugo](https://gohugo.io/getting-started/quick-start/#step-1-install-hugo) and [create a new site](https://gohugo.io/getting-started/quick-start/#step-2-create-a-new-site). Afterwards, you can install Mainroad theme. No special compilation is required. If you want to run Hugo site in server mode, you can use [hugo server mode](https://gohugo.io/commands/hugo_server/).

P.S. Please, use english only messages in issues.

**Comment by it-spectre-ru** [comment]
hello, thx a lot. i need build hugo and this infomation can't find. it simle comant `hugo` and site build in /public root
