### ISSUE TITLE
Can't add my favortie icon + add tags/categories?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Vimux/Mainroad#107]
i tried add icon for website but it's appear in local host but when i upload it to github pages, i see old fav icon + how add my tags/categories to posts ?

**Comment by Vimux** [comment]
1) Replace favicon.ico file (`/static/favicon.ico`)
2) See `tags` and `categories` params in [Mainroad Front Matter Example](https://github.com/Vimux/Mainroad/blob/master/README.md)
