### ISSUE TITLE
how fix search ?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Vimux/Mainroad#108]
well, thx for helping about fav.ico, i feel it's kind bug from your side (because all other themes working good, but your theme must add icon in specific location) & now i keep switching to google search every time i try to use search in your theme so is there anyway to fix it & make search engine work inside my website ?

**Comment by Vimux** [comment]
> i keep switching to google search every time i try to use search in your theme so is there anyway to fix it & make search engine work inside my website ?

This is the standard search behavior in Mainroad theme.

> thx for helping about fav.ico, i feel it's kind bug from your side (because all other themes working good, but your theme must add icon in specific location) 

Don't use Mainroad. Use another theme from Hugo themes repository or create your own theme with features that you need. Simple and easy.

**Comment by EsmailELBoBDev2** [comment]
i knew hugo from 3 days ago... :3
