### ISSUE TITLE
error deploy mainroad netlify

### ISSUE THREAD

**Issue by fervilber** [Vimux/Mainroad#109]
When deploying a website from Github on netlify using mainroad hugo theme I receive the following message:
ERROR: ...template.go:477: template: theme/partials/footer.html:5: function "now" not defined
3:04:05 PM: ERROR: 2019/01/03 .... template.go:477: template: theme/partials/sidebar.html:1: function "newScratch" not defined
3:04:05 PM: ERROR: 2019/01/03 ... general.go:212: Error while rendering taxonomy tag: template: /opt/build/repo/themes/Mainroad/layouts/_default/baseof.html:15:23: executing "/opt/build/repo/themes/Mainroad/layouts/_default/baseof.html" at <.OutputFormats.Get>: can't evaluate field OutputFormats in type *hugolib.Node

**Comment by Vimux** [comment]
Hello, @fervilber 

Looks like that you use very old Hugo version. Mainroad depends from Hugo 0.43 as minimum version. It should work correctly in that (or newer) version.

**Comment by fervilber** [comment]
Thanks, ... netlify uses 0.2 Hugo version, so it will be the problem. 
A pity I like mainroad

**Comment by Vimux** [comment]
It's not a problem. Please read [Host on Netlify](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/). I'm sure that Netlify also contains similar documentation.
