### ISSUE TITLE
Social Media widget

### ISSUE THREAD

**Issue by matheusrocha89** [Vimux/Mainroad#11]
Hi @Vimux do you have plans to create this widget or is already working on? Can I help you with something?

**Comment by Vimux** [comment]
Hi, @matheusrocha89

Thank you for your curiosity. I have a plan to implement social media widget. If I need help with this, I'll write about it.

**Comment by matheusrocha89** [comment]
Ok, so I will not open the PR for that, I will try to work on remove the unused CSS. It's OK for you @Vimux ?

**Comment by Vimux** [comment]
Okay, but **be extremely careful with CSS**. Do not remove usefull.

**Comment by matheusrocha89** [comment]
Ok @Vimux I am looking if the class is used somewhere, if not I will remove. And before I open the PR I will test locally.

**Comment by matheusrocha89** [comment]
@Vimux there are some classes that starts with `mr` that are not used anywhere, they are created dynamically in any `html` or car I just remove them? I saw some created by `JS` and I let them there, but these ones I didn't find anywhere they have been used.

**Comment by matheusrocha89** [comment]
@Vimux Now that we removed not used css what we can do now? Need help o social widget? There is another task with high priority that I can do?

**Comment by Vimux** [comment]
If you wish, you can create a social media widget.

**Comment by matheusrocha89** [comment]
Ok, I will do that. 👍
