### ISSUE TITLE
Syntax Highlighting for code 

### ISSUE THREAD

**Issue by fervilber** [Vimux/Mainroad#111]
Is There a Syntax Highlighting parameter for code chunks? 
The default mode is only grey background for code.

**Comment by Vimux** [comment]
It's default theme behaviour for code blocks.

You can use Chroma Highlighter Please read [Syntax Highlighting](https://gohugo.io/content-management/syntax-highlighting/) and check [this demo page](https://themes.gohugo.io//theme/mainroad/post/basic-elements/).
