### ISSUE TITLE
i18n doesn't work

### ISSUE THREAD

**Issue by rjbudzynski** [Vimux/Mainroad#115]
To reproduce:

- hugo new site mainroad-test
- cd mainroad-test/themes
- git clone https://github.com/vimux/mainroad
- cd mainroad/exampleSite
- cp -r \* ../../..
- cd ../../../
- *edit config.toml changing `languageCode` to "es"* (or "es-es", not sure which is supposed to be correct, but the effect is the same)
- hugo server
- open localhost:xxxx/ in your browser, verify that "SEARCH", "Read more" etc. are still in English.

**Comment by Vimux** [comment]
`defaultContentLanguage`

https://gohugo.io/getting-started/configuration/#all-configuration-settings
