### ISSUE TITLE
Newbie: You don't have any posts yet!

### ISSUE THREAD

**Issue by pmorch** [Vimux/Mainroad#120]
I tried to follow https://gohugo.io/getting-started/quick-start/

But I wanted to use the mainroad theme instead of ananke.

This is what it looks like in ananke:
![selection_012](https://user-images.githubusercontent.com/159292/53372096-4ccb3c80-3952-11e9-9901-4901d79201f5.png)

And this is what it looks like with mainroad:
![selection_013](https://user-images.githubusercontent.com/159292/53372111-52288700-3952-11e9-9a06-c3a623db5934.png)

I think I have posts since ananke (and hamburg) can show them. Or what am I doing wrong? To reproduce:

    hugo new site foobar
    cd foobar
    echo 'theme = "mainroad"' >> config.toml
    git clone https://github.com/vimux/mainroad themes/mainroad
    # git clone https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
    hugo new posts/foo.md
    hugo serve -D

hugo version: Hugo Static Site Generator v0.54.0-B1A82C61 linux/amd64 BuildDate: 2019-02-01T09:40:34Z

**Comment by Vimux** [comment]
# As posts are added in ***content/post*** folder, they'll appear here

You use `posts`, not `post` folder. Two options:

1. `hugo new post/foo.md`
2. Add `posts` in config.toml file `postSections` param:

```
[Params]
  postSections = ["post", "posts"]
```

**Comment by pkel** [comment]
@Vimux: I think it might be worth changing our default to `posts` instead of `post`. For Newcomers who follow the [quick start tutorial](https://gohugo.io/getting-started/quick-start/) it would be much easier then.

One could even think about including all sections if `postSections` is not defined.

**Comment by Vimux** [comment]
We should just change `postSections` to `mainSections`.

https://gohugo.io/functions/where/#mainsections

I also want to change some other theme config params (like `disable_comments` → `comments` invert logic), drop IE10 support, bump Hugo version (I remember about #80 + #103), drop Google+, simplify post meta fields logic (delete "none" meta field, disable all meta fields by default)...

I think it is better to do this at the same time and not to produce breaking changes every time. Main obstacle: no spare time for Github and other stuff in the next few weeks.

**Comment by pkel** [comment]
Sounds good. No pressure from my side. Perhaps I find some time for one or two of the mentioned points.
