### ISSUE TITLE
Adding a link in the bio of config.toml

### ISSUE THREAD

**Issue by paleomariomm** [Vimux/Mainroad#122]
I would like to add a link to my web in [Authors] bio = (in the config.toml). I tried with HTML and Markdown code without success.  Any idea?

This is my code snippet:

```
[Author]
  name = "Mario Modesto Mata"
  bio = "Biólogo y Paleoantropólogo. Apasionado de la Estadística y la programación en R. Visita  mi web [modestomata.com](http://modestomata.com/)"
  avatar = "img/avatar.jpg"
```

**Comment by Vimux** [comment]
Change this line in authorbox.html:
https://github.com/Vimux/Mainroad/blob/1ff500f3afc9503b0225f2fe62c363c5edd4f3fe/layouts/partials/authorbox.html#L18

```
{{ . | markdownify }}
```

**Comment by paleomariomm** [comment]
Thanks so much Vimux! **And how can I change link color**? Be default it has the same color as the other text...

**Comment by paleomariomm** [comment]
I discovered it, by modifying the `style.css` (in `themes/Mainroad/static/css`)
```
a {
	color: #1d0088;
	text-decoration: none;
}
```
