### ISSUE TITLE
Adding a banner as header of the web

### ISSUE THREAD

**Issue by paleomariomm** [Vimux/Mainroad#123]
I use your Mainroad theme in my web.

However, I would like to add a banner, which is an image, instead of the title of the web. How can I edit the code to implement the image?

**Comment by Vimux** [comment]
I didn't quite understand the requirement, but if you want to replace the site title with an image, then you need to change these two lines with your image:

https://github.com/Vimux/Mainroad/blob/1ff500f3afc9503b0225f2fe62c363c5edd4f3fe/layouts/partials/header.html#L5-L6

You can try something like that (not tested):

```
<img src="{{ .Site.Params.siteBanner | relURL }}">
```

**Comment by paleomariomm** [comment]
Perfect. I tested your codes and they worked nicely!

**Comment by jhalbrecht** [comment]
I'd like to see the enhancement label on this. ?? :-)

I wanted something similar. I didn't want to replace the title and subtitle I wanted to _add_ a banner image. I accomplished it by following @Vimux code and wrapping it in a conditional.

```
<div class="logo">
	<a class="logo__link" href="{{ "" | relLangURL }}" title="{{ .Site.Title }}" rel="home">
		<div class="logo__title">{{ .Site.Title }}</div>
		{{ with .Site.Params.subtitle }}<div class="logo__tagline">{{ . }}</div>{{ end }}
		{{ if .Site.Params.siteBanner }} <img src="{{ .Site.Params.siteBanner | relURL }}"> {{ end }}
	</a>
</div>
```

FWIW it can be seen on my, currently a sandbox, site; [homeamation.net](https://www.homeamation.net/)

discussion could be 
* to add a config for it to display on mobile or not...
* Fill a bit further to meet the edges of the menu
