### ISSUE TITLE
SEO Titles different than page or post title

### ISSUE THREAD

**Issue by eduardomachuca** [Vimux/Mainroad#128]
Hola,

I come from WordPress and wanted to have the SEO functionality of Yoast and similar SEO plugins.

Anyway, I made the following code to be able to have a SEO title different from the document title used within the site.

In config.toml, add, under [Params] (and keep Site Title as is):

[Params]
  homeSeoTitle = "home page SEO title shown on browser or search results" #less than 60 chars or 580 pixels.

In your site's /archetypes/default.md or /archetypes/post.md front matter, add (keep Title as is):

title: "{{ replace .TranslationBaseName '-' ' ' | title }}" # Document title used within the blog
seotitle: "SEO title for browser and search engines" # SEO title 60 chars max. or 580 pixels

If you already have content in your site (pages, posts), add seotitle to the front matter:
seotitle: "SEO title for browser and search engines" # SEO title 60 chars max. or 580 pixels

Copy baseof.html from /themes/mainroad/layouts/_default to your site's /layouts/_default/baseof.html

Edit your site's baseof.html and substitute the whole line:
<title>{{ block "title" . }}{{ if not .IsHome }}{{ .Title }} - {{ end }}{{ .Site.Title }}{{ end }}</title>

with:

<title>{{ block "title" . }}
		{{ if .IsHome }}
		    {{ .Site.Params.HomeSeoTitle }}
		{{ else }}
		    {{ .Params.Seotitle }}
		{{ end }}
{{ end }}</title>

Now you can set a Title for the document internal naming within the site or blog, and a different SEO title to be shown on the browser or in search engines.

A word of caution, I don't know the slightest thing about Hugo nor Golang. I think there are other places within the theme or Hugo's code that will probably use the Site Title. I arrived at this solution by watching how the code was written and experimenting. Use at your own risk.

---

Also, another thing I wanted to have was a different url than the one created by default by the post's Title, also for SEO purposes (to avoid keyword repetition or to target secondary keywords in the url).

For that, I added, in config. toml:

relativeURLs = true

[permalinks]
  post = "/:slug/"

And, in /archetypes/default.md and /archetypes/default/post.md, I added to the front matter:

slug: "your-custom-url" #Important to enter! This is the post or page actual url!

Also add the
 slug: "your-custom-url" 
the front matter of any page or post you already have.
Can be the same url you already have for that page or post, but could also be different now, just be aware that if you change urls already indexed by search engines, you may need to do 301's redirects from the old to the new url.

Again, my site is working with the Mainroad theme, but can't guarantee that will work for yours.

Also, I don't know how Git/github works but maybe this could be reviewed and corrected and added to the next theme's version.

Saludos,

Eduardo

**Comment by Vimux** [comment]
I'm glad you've done what you've done, but I don’t understand why you publish this here.
Issues are not personal notes or something like that, it's for issues, bugs, etc.
Start a personal blog, if you want to share notes with others.

Thank you!
