### ISSUE TITLE
Content in lists is squashed on homepage

### ISSUE THREAD

**Issue by cdyson37** [Vimux/Mainroad#130]
If I create a post with markdown lists, these render correctly when the post is viewed directly, but on the homepage they are squished into a single paragraph. Is there a way to disable this? (I can hide them using the `<!--more-->` directive, but cannot find any documentation for that.)

Sorry if it's something obvious I've missed! I would have contacted directly rather than open an issue but couldn't find an email address.

**Comment by pkel** [comment]
Mainroad uses the `.Summary` variable for generating the entry on the homepage. You can use `<!--more--` to cut off the list or provide an alternative summary in the front matter.

**Comment by cdyson37** [comment]
Got it! This is the documentation I was looking for but failed to find - and nothing specific to this theme: https://gohugo.io/content-management/summaries/

Thanks!
