### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by DarkiStar** [Vimux/Mainroad#131]
Is it possible to access images as thumbnails from the same directory where the index.md file is located (content/post/newpost/index.md?

I tried to change the following in layouts/_default/summay.html

`<a href="{{ .Permalink }}">`
to
`<a href="{{ .RelPermalink }}">`

and it looks like it worked, but not for all posts, only the first one.

regards

**Comment by Vimux** [comment]
Hello!

I can't figure out the problem, because your message looks "broken" (sort of). Please clarify your problem in the new comment.

**Comment by DarkiStar** [comment]
Hello,

this is my structure:

site/content/post/firstPost/
    index.md
    image.jpg


index.md looks like this
---
title: "first Post"
date: 2019-05-19T00:00:00+02:00
thumbnail: "image.jpg"
draft: true
---
test post

![](image.jpg)

----------------------

I would like to show image.jpg als thumbnail in the main menu. (without copying it to the static folder).

**Comment by Vimux** [comment]
Take a look at [The Image Page Resource](https://gohugo.io/content-management/image-processing/#the-image-page-resource) section.

You need to modify some partials (summary.html, single.html) to get specific image page resource ("thumbnail.*" in the example) from page bundle.

Quick raw example:

```
{{ $img := (.Resources.ByType "image").GetMatch "thumbnail.*" }}
{{ with $img }}
	<img src="{{ $img.RelPermalink }}">
{{ end }}
```

REF:
https://gohugo.io/content-management/image-processing/#the-image-page-resource
https://gohugo.io/content-management/page-resources/#methods

**Comment by DarkiStar** [comment]
I fixed my first posting above. 

Even changing .Permalink to .RelPermalink does not lead to the desired effect.

```
<article class="list__item post">
	{{- if .Params.thumbnail }}
	<figure class="list__thumbnail">
		<a href="{{ .RelPermalink }}">
			<img src="{{ .Params.thumbnail | relURL }}" alt="{{ .Title }}" />
		</a>
	</figure>
	{{- end }}
.
.
.

```
Only if the image is copyied in addition into the static folder, it will be found and displayed as thumbnail in the summary page. 

In which file should I put your suggested code? Summary.html?
I am confused ... (new to hugo and go).

regards

**Comment by Vimux** [comment]
> In which file should I put your suggested code? Summary.html?

You need to modify summary.html and single.html as I stated in my previous message.

You should replace the current thumbnail code to quick raw example from my previous message. After that put any "thumbnail.*" image in page bundle.

> Even changing .Permalink to .RelPermalink does not lead to the desired effect.

Is there any mention in the official documentation that this should work? Nope.

**Comment by Vimux** [comment]
Closed because no response.
