### ISSUE TITLE
Can't add page to Main Menu

### ISSUE THREAD

**Issue by ludwa6** [Vimux/Mainroad#135]
The ReadMe says: "In order to add a page to a menu, add a `menu = <menu>` parameter to the pages frontmatter."  

Taking this instruction literally at first, I simply copy/pasted the string `menu = <main>` into TOML metadata section on top of my "about.md" page and rebuilt (using the Blogdown package in RStudio, in case that matters)... But that threw an error message into my console, 

> Error building site:  failed to unmarshal YAML: yaml: line 6: could not find expected ':'

So, reinterpreting the instruction with my understanding of correct syntax, (i.e. : in place of =), I replaced the above code with `menu: main` , and that worked to populate the main menu bar (previously empty)... Only now that menu appears with an item at far RH side called "MENU", which does not link to the "about" page as intended.

Would appreciate a bit more detailed HowTo on this than what's presently in the ReadMe.

**Comment by Vimux** [comment]
Hello.

Screenshot, please.

**Comment by ludwa6** [comment]
Dunno how this helps, but here you can see the menu bar in context:
![BlogHeader](https://user-images.githubusercontent.com/1822101/60130099-77a59000-978e-11e9-8ba8-0bae5b18d009.jpeg)

**Comment by Vimux** [comment]
What about [Mainroad demo](https://hugothemes.gitlab.io/mainroad/)? Main menu works correctly in the demo site? If yes, it looks like something wrong in your menu configuration. Check [Hugo Menus](https://gohugo.io/content-management/menus/) documentation.

**Comment by ludwa6** [comment]
OK @Vimux :  the "Mainroad demo" site shows up fine in my browser (Chrome Version 75.0.3770.100 (Official Build) (64-bit)), main menu bar with page links and all... 

So i just created a new blog, accepting all defaults, without any additions or modifications of content or code, and it installs perfectly, all works as per the demo site, EXCEPT the menu bar appears exactly as per my screenshot above.  The TOML frontmatter on the "About Hugo" page looks like this:
```
---
authorbox: false
date: "2014-04-09"
menu: main
sidebar: false
title: About Hugo
---
```

... But then the config.toml file makes no mention of the word "menu".  So, following your reference to Hugo Menus docs, i saw where it suggested that i might add the following code to my config.toml file : 

```
[menu]

  [[menu.main]]
    identifier = "blog"
    name = "This is the blog section"
    title = "blog section"
    url = "/blog/"
    weight = -110
```

...and so i did; was able to save and serve site with no error msg in my RStudio console, but then it made no difference to the problem: menu bar remains with just the word MENU at far right, which turns red on click, and back to white on reclick, but links to nothing.

So @Vimux : is there anything else you can suggest? I love this theme, it presents my blog content exactly the way i want and is perfect in all other respects, but i do need that menu bar with links to a few persistent pages of content.  I appreciate your attention to this issue.

**Comment by ludwa6** [comment]
Update: problem solved; this display problem was a function of my viewing site in a (constrained) frame, but when i opened in its own browser window, everything appeared as it should.  Am not sure i agree with the way main menu bar adapts to a smaller view frame -will be interesting to view in portable devices, once i bring it online- but you can call this issue close, @Vimux -thanks!
