### ISSUE TITLE
Can I customize CSS?

### ISSUE THREAD

**Issue by CicoZhang** [Vimux/Mainroad#137]
I would like to change CSS a little bit for a slightly different style, can I customize CSS like in other themes? Thanks in advance.

**Comment by Vimux** [comment]
Hello.

Use `customCSS` parameter to achieve that. REF: [Config.toml example](https://github.com/Vimux/Mainroad#configtoml-example)

**Comment by CicoZhang** [comment]
Thank you for the help. I got it working.
