### ISSUE TITLE
simple custom widget

### ISSUE THREAD

**Issue by jhalbrecht** [Vimux/Mainroad#138]
In the README.md there are two links to two sample sites; Demo (Fast update) | Standart Demo

The "Demo (Fast update)" site has a "SUPPORT US" on the bottom of the right hand column that I assume is a sidemenu? I'd like to learn how to accomplish something similar. I'm wondering if I (we) could please have access to the source code for that site to see how it was accomplished?

I've been dinkin' around RTFM and such, looked at issue #134 "Add blogroll" I could probably answer my own question by browsing the source for that site; "Demo (Fast update)"

</Insert obligatory Hugo nOOb statement here>
Mainroad is great for what I want in my [Homeamation.net](https://www.homeamation.net/) blog. tags, categories, thumbnail... along with the [hugo-easy-gallery](https://github.com/liwenyip/hugo-easy-gallery) with it's ~~img~~ figure  shortcode overide I'm well on the way to a solution that's right for me. Thank you for maintaining Mainroad.

**Comment by Vimux** [comment]
> The "Demo (Fast update)" site has a "SUPPORT US" on the bottom of the right hand column that I assume is a sidemenu?

No, this is just a simple custom widget:

```html
<div class="widget-text widget">
	<h4 class=widget__title>Support us</h4>
	<div class=widget__content>
		<p>If you like <strong>Mainroad</strong> theme, remember that you can show
		your support by starring it on Github. It only takes a couple of seconds!</p>
		<iframe src="https://ghbtns.com/github-btn.html?user=vimux&repo=mainroad&type=star&size=large&count=true"
			title="Github star button with counter"
			style="border:0;overflow:hidden"
			width="160"
			height="30">
		</iframe>
	</div>
</div>
```

> I'm wondering if I (we) could please have access to the source code for that site to see how it was accomplished?

Demo site generated from [exampleSite](https://github.com/Vimux/Mainroad/tree/master/exampleSite) content.

> ...looked at issue #134 "Add blogroll"...

Not relevant.

**Comment by jhalbrecht** [comment]
O.K. I got it with some google developer tools and MS Code search in files.

I modified your .html above as **myblogs.html** and placed it in **/layouts/partials/widgets/** Then in **config.toml** I added **myblogs** to the **widgets** array in the **[Params.sidebar]**.
