### ISSUE TITLE
thumbnail enhancement?

### ISSUE THREAD

**Issue by jhalbrecht** [Vimux/Mainroad#140]
I like the front matter thumbnail: and lead: options. However I didn't care for the size of the thumbnail on the actual page.

I solved it in custom.css with; 

```
.post__thumbnail img {
	width: 25%;
}
```

One more change I'd like to make, that I don't know how to accomplish, I think might make a useful enhancement. Perhaps a 'flow: side' with a default of 'flow:bottom' along with thumbnail: and lead: in the front matter to modify  how the body post text flows around the thumbnail in the body of the post.

I would like for the text of my post to start at the top of the page adjacent to the image and flow down around the thumbnail until it fills the page width once it reaches the first line below the thumbnail. Rather than the current body text starting at the line below the bottom of the thumbnail image.

**Comment by Vimux** [comment]
> Perhaps a 'flow: side' with a default of 'flow:bottom' along with thumbnail: and lead: in the front matter to modify how the body post text flows around the thumbnail in the body of the post.

> I would like for the text of my post to start at the top of the page adjacent to the image and flow down around the thumbnail until it fills the page width once it reaches the first line below the thumbnail. Rather than the current body text starting at the line below the bottom of the thumbnail image.

Sorry, I do not plan to do something similar to this, not in my priorities. If you need something like that, then dig to the CSS (floats).

**Comment by Vimux** [comment]
I'll close this. As I said earlier, I don't plan to do this and I don’t think that anyone else will take it.
