### ISSUE TITLE
Can I Remove package.json

### ISSUE THREAD

**Issue by furkantokac** [Vimux/Mainroad#144]
What is the use of package.json for this theme ? I'm not planning to use npm or something, I'll just host my blog on GitHub or GitLab. If I remove package.json, do I have any problem or lack of feature for the theme ?

btw. thanks for the theme! Great work.

**Comment by oshliaer** [comment]
As I can see the project uses this for building the theme but not for using it. What is prevented you from simply killing this file and its relatives?

**Comment by furkantokac** [comment]
@oshliaer I think the same so I removed it but just wanted to be sure if I face any problem or not on the page side. So thank you. I close the issue.
