### ISSUE TITLE
Unable to add text sidebar widget

### ISSUE THREAD

**Issue by wojciehm** [Vimux/Mainroad#149]
Hi there.

I want to add some ads to the widget displayed on the right side of the page.

I've created ads.html in widgets folder with the following content

```
{{- if isset .Site.Taxonomies "ads" }}
{{- if not (eq (len .Site.Taxonomies.ads) 0) }}
<div class="widget-categories widget">
	<h4 class="widget__title">{{ T "ads_title" }}</h4>
	<div class="widget__content">
	<p>SOME TEXT</p>	
	</div>
</div>
{{- end }}
{{- end }}
```

I added ads to widgets section in config.toml
```
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["ads", "search", "social","recent", "categories", "languages"]
```
Text/widget isn't displayed.

**Comment by Vimux** [comment]
Hello.

You tried to modify the category widget but didn't do it correctly, because of unnecessary checks above the widget.

Originally, these checks ensure that "categories" taxonomy exists and not quals zero. In your case, "ads" taxonomy not even created (and you don't have to do this). Use this as a starter template for your `ads.html` widget:

```html
<div class="widget-ads widget">
	<h4 class="widget__title">Ads</h4>
	<div class="widget__content">
		<p>SOME TEXT</p>
	</div>
</div>
```

**Comment by wojciehm** [comment]
Thanks for the hint and please excuse Hugo noobiness.

 In /layouts/partials/widgets I created ads.html. However it is not displayed on the webpage. What do I have to do to display it properly?

<img width="726" alt="image" src="https://user-images.githubusercontent.com/19718255/67681551-d6258980-f98d-11e9-921a-a82b317a5fb8.png">

**Comment by Vimux** [comment]
That means that you made a mistake somewhere else.

1. Ensure that your widget path is correct:

```
.
├── layouts
│   └── partials
│       └── widgets
│           └── ads.html
└── themes
    └── Mainroad
``` 

2. Check your config widget & sidebar positioning params. For example, activate sidebar on the right side for all pages:

```toml
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["ads", "search", "social","recent", "categories", "languages"]
```

3. Ensure that you don't use Adblock at this moment. Check again in the incognito mode without any adblockers.

**Comment by wojciehm** [comment]
It worked. Thanks a lot for help. Awesome theme :)
