### ISSUE TITLE
Would it be possible to add Youtube?

### ISSUE THREAD

**Issue by JuliusTZM** [Vimux/Mainroad#151]
Dear Vimux,

I miss the YouTube and IRC social icon. Would it be possible to add?

Thanks

**Comment by Vimux** [comment]
Thank you for the suggestion. Yes, it is possible. You can always add them through a Pull Request.

**Comment by yuqingc** [comment]
Would it be possible to add customized social links and icons via `config.toml` file? There are issues where their authors wanted to add extra social widgets. Why not just let users add their own social widgets by adding them to the `config.toml` file?

**Comment by Vimux** [comment]
Hello,

> There are issues where their authors wanted to add extra social widgets. Why not just let users add their own social widgets by adding them to the `config.toml` file?

As I mentioned in my previous comment, Pull Requests are always open to everyone.

**Comment by yuqingc** [comment]
@Vimux Thanks. I'll open a pull request for this feature :)

**Comment by yuqingc** [comment]
Hi, I opened a PR (#159 ) for customizing sicial widgets.
