### ISSUE TITLE
Using custom fonts with mainroad theme

### ISSUE THREAD

**Issue by nandac** [Vimux/Mainroad#155]
Hi Mainroad team,

I would first like to thank all the contributors for the excellent documentation.

I have a question about how to use custom fonts with this theme, I know that other themes have hooks where a user could customize the fonts using the config.toml file.

Does mainroad have such hooks or would I have to use a custom CSS file to achieve the desired effect?

I am quite new to Hugo but have several years of Web development experience and would like to get guidance on what would be the recommended Hugo method to use custom fonts.

In addition is custom font support be available in a future release of this theme?

Looking forward to your reply.

**Comment by Vimux** [comment]
Hello,

> Does Mainroad have such hooks...

No. See #150. This PR does not meet the requirements, but perhaps it will be useful for you.

> ...or would I have to use a custom CSS file to achieve the desired effect?

It depends from your needs. Technically yes, you can use custom CSS.

> ...is custom font support be available in a future release of this theme?

I can't say anything about this.
