### ISSUE TITLE
Categories with latin2 characters are not displayed in post meta

### ISSUE THREAD

**Issue by janicetr** [Vimux/Mainroad#156]
Categories with latin2 character(s) are displayed properly in the categories widget, but do not show up in the post meta. Maybe a parsing issue? They are UTF-8 encoded in the front matter.

**Comment by Vimux** [comment]
Hello,

Maybe you should provide an example at least?

**Comment by janicetr** [comment]
Sorry. I made a screenshot. The "Hírek" category name contains an i with an acute accent. I tried some other acute and double acute characters, they have  the same problem. The relevant span section in the generated html is empty. Windows x64 version Hugo running on Win10 x64.

![mainroad](https://user-images.githubusercontent.com/15192336/69264440-9ede7d00-0bc7-11ea-8c15-6c02cb77c59b.jpg)

**Comment by Vimux** [comment]
I reproduced this, but I'm not sure that this is the theme related issue. Briefly: the main problem that we can't get a page from a generated link that contains complex symbols. Related code line: https://github.com/Vimux/Mainroad/blob/4ab228789f774189a918e2b881001cb56b3c5f67/layouts/partials/post_meta/categories.html#L8 .GetPage just return noPage. Maybe .GetPage cannot handle such cases correctly.

I don't have time to investigate this right now. I'll be back later, as soon as I have time for this. I will not mark this as a theme bug right now.

**Comment by Vimux** [comment]
I prepared a bugfix for this.

I tried to follow the Hugo documentation example for taxonomy templates, but it should not be trusted right now, in this particular example, at least.

@janicetr, thank you for reporting this.

**Comment by Vimux** [comment]
Unfortunately, `anchroze` don't solve this bug completely:

```
foo(bar) | anchorize   ->   foo-bar
foo(bar) | urlize      ->   foobar
```

I prepared another fix. 😕

---

Big thanks to @reuixiy for clarification.
