### ISSUE TITLE
Hugo version 0.57+ breaks site structure

### ISSUE THREAD

**Issue by wojciehm** [Vimux/Mainroad#157]
With the release of Hugo 0.57+ site functionality is broken. 
When this part of the code is uncommented site title appears before first post.
https://github.com/Vimux/Mainroad/blob/4ab228789f774189a918e2b881001cb56b3c5f67/layouts/_default/list.html#L5

![image](https://user-images.githubusercontent.com/19718255/69547655-4c6dd980-0f96-11ea-8179-a33350964581.png)

When it is commented it doesn't appear at top of the posts but it is gone from main menu.
![image](https://user-images.githubusercontent.com/19718255/69547765-6f988900-0f96-11ea-8703-d81c8f347bce.png)

Thanks in advance for looking into it.

**Comment by Vimux** [comment]
Hello,

If you state "with the release of Hugo 0.57+ site functionality is broken", please, can you provide side-by-side screenshots, when Hugo 0.56 works correctly and Hugo 0.57+ doesn't? As well as all other useful information, as required by [CONTRIBUTING reporting bugs section](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md#issues).

And of course, this should be running with the HEAD version of the Mainroad [[4ab228789f774189a918e2b881001cb56b3c5f67](https://github.com/Vimux/Mainroad/tree/4ab228789f774189a918e2b881001cb56b3c5f67)].

> When this part of the code is uncommented site title appears before first post.

It's a page title, not site title.

> When it is commented it doesn't appear at top of the posts but it is gone from main menu

I see identical menus in both of your screenshots. Logically, the first screenshot should contain something, that "is gone from main menu" in the second image, right? I don't see any difference.

This information is not enough to confirm the issue. Please, can you provide more information? Right now, I see a page with a page title. That's all.

**Comment by wojciehm** [comment]
I downloaded your theme again and implemented my changes. Now everything works. Sorry for confusion.
