### ISSUE TITLE
Questions about pages in Hugo

### ISSUE THREAD

**Issue by wojciehm** [Vimux/Mainroad#158]
Hi.

Suddenly my pages which are located in the main menu appear in blog post feed. The pages have following content
`---
title: Veeam
author: Wojciech Marusiak
type: page
date: 2017-05-16T14:26:55+00:00
menu: main
---`

Posts following content: 

```
---
title: Some title
date: 2019-11-13T10:29:37+01:00
author: Wojciech Marusiak
draft: false
categories:
  - Cat1
tags:
  - Tag1
---
```

Hi can I prevent pages to appear in posts? Live site [https://www.wojcieh.net/](https://www.wojcieh.net/)
Pages displayed in the posts feed:

- [https://www.wojcieh.net/about-me/](https://www.wojcieh.net/about-me/)
- [https://www.wojcieh.net/advertise/](https://www.wojcieh.net/advertise/)
- [https://www.wojcieh.net/contact/](https://www.wojcieh.net/contact/)
- [https://www.wojcieh.net/veeam/](https://www.wojcieh.net/veeam/)
![image](https://user-images.githubusercontent.com/19718255/69548668-0ade2e00-0f98-11ea-88ce-f816edb24127.png)

Thanks in advance.

**Comment by Vimux** [comment]
Hello,

> Suddenly my pages which are located in the main menu appear in blog post feed. The pages have following content...

There is no difference between posts and pages in Hugo by default. As a result, all of the content pages (no matter what section) included in the standard RSS feed.

> can I prevent pages to appear in posts?

I don't quite understand you, but if you don't want to show some sections on the front page, use `mainSections` param to provide a list of front page sections. All other sections will be ignored.

**Comment by wojciehm** [comment]
I downloaded your theme again and implemented my changes. Now everything works. Sorry for confusion.
