### ISSUE TITLE
Option to disable showing thumbnail inside post

### ISSUE THREAD

**Issue by dboso** [Vimux/Mainroad#160]
I would like to be able to set a thumbnail on a post, but not showing the thumbnail when a user opens the post (single.html)
Until now I have been modifying the theme to achieve this by removing the logic that sets the picture inside single.html (see below)

Suggestion: consider a config option to disable the thumbnail picture inside a post

Cheers

**Comment by m1hax** [comment]
Any chance of getting this implemented please? There is a pending pull request with a good implementation to resolve this request from over a year ago.
