### ISSUE TITLE
Link not higlighted on main navigation menu

### ISSUE THREAD

**Issue by nandac** [Vimux/Mainroad#161]
Hi,

I need some guidance on how to get the active link highlighted in the main navigation bar. I am fairly new to hugo and have gone through the docs but not able to figure this out.

I have my menu items declared in config.toml. However I am only able to get the active link highlighted for the blogs page which is the last link in the list below:

```
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "sas"
    name = "SAS"
    url = "/sas/"
    weight = 3

  [[menu.main]]
    identifier = "colophon"
    name = "Colophon"
    url = "/colophon/"
    weight = 4

  [[menu.main]]
    identifer = "blog"
    name = "Blogs"
    url = "/blog/"
    weight = 5
```
My content is structured like so:
```
── content
│   ├── about.pdc
│   ├── blog
│   │   ├── blog-1.pdc
│   │   ├── blog-2.pdc
│   │   ├── blog-3.pdc
│   │   └── blog-4.pdc
│   ├── colophon.pdc
│   ├── index.pdc
│   └── sas.pdc
```
Furthermore, I would like to switch off certain features like post navigation on some pages. I tried doing it in the frontmatter like this:
`post_navigation: false`

but that did not work.

I would appreciate any pointers you may have to get this working.

Cheers,
Nanda

**Comment by contributorpw** [comment]
Hi @nandac !

There is all what you need to know about navigation highlight:

- [Hugo applies the class `menu__item--active`](https://github.com/Vimux/Mainroad/blob/03afed62e0287568b445e3c2ae3db3e2e08c1d68/layouts/partials/menu.html#L10)
- [css style](https://github.com/Vimux/Mainroad/blob/2dd3780f30a4c7d253609e7c2821ec87efea64e3/assets/css/style.css#L484)

You can apply  the class `menu__item--active` to anything you want. You have to override layouts, partials as Hugo needs it.

**Comment by contributorpw** [comment]
Hi @nandac !

As you can see [#](https://github.com/Vimux/Mainroad/blob/faee0253f5e0d4f14e40dc7e41c010fd178920d2/layouts/partials/post_nav.html#L1) only post layouts has `post_navigation`

**Comment by nandac** [comment]
Thank you for your reply @contributorpw. I have got it working now.

**Comment by Vimux** [comment]
It seems like the question has been solved. I am going to close out this issue for now.
