### ISSUE TITLE
Search on demo site does not work

### ISSUE THREAD

**Issue by nandac** [Vimux/Mainroad#165]
Hi Mainroad Team,

Thank you for developing this theme. You have saved me hours of design work. :-)

The site search on the [demo site](https://themes.gohugo.io//theme/mainroad/tags/emoji/) does not work correctly.

I think it may be because it is searching on this URL: https://themes.gohugo.io**//**theme/mainroad/

which has two forward slashes as highlighted above.

I just thought I should let you know so that it can be fixed.

Cheers.

**Comment by contributorpw** [comment]
I think the trouble on the _themes.gohugo.io_'s side.

The single slash works fine [emoji site:https://themes.gohugo.io/theme/mainroad/](https://www.google.com/search?q=emoji%20site:https://themes.gohugo.io/theme/mainroad/)

**Comment by Vimux** [comment]
@nandac Hi,

I am going to close out this issue because it is not related to the theme directly.

> I think it may be because it is searching on this URL: https://themes.gohugo.io**//**theme/mainroad/ which has two forward slashes as highlighted above.

This.
