### ISSUE TITLE
Social/custom widget doesn't appear

### ISSUE THREAD

**Issue by Eliesemoule** [Vimux/Mainroad#166]
Hello,

I have an issue. Social widget doesn't appear in right colum (Widget colum). I use Hugo 0.62.2.
Here my config.toml

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  widgets = ["social", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  github = "Eliesmoule"

[[Params.widgets.social.custom]]
  title = "My Home Page"
  url = "http://example.com"

Do you have any idea where is the problem ?

**Comment by Vimux** [comment]
@Eliesemoule Hello,

I don't see anything strange in this configuration. Most likely, you were mistaken somewhere else. That's all I can say.

**Comment by Eliesemoule** [comment]
Hello @Vimux ,

Thank you for your reply
I confirm that it works. There was a bug with my browser's cache.
