### ISSUE TITLE
List pages not working for directories other than post directory

### ISSUE THREAD

**Issue by grenmester** [Vimux/Mainroad#17]
I was using your theme and I was trying to get the section pages to work. This is what my `content` directory looks like.

```
.
├── about.md
├── new-section
│   ├── _index.md
│   └── article.md
└──  post
    ├── _index.md
    ├──  activities.md
    └── ...
```

When I go to [localhost:1313/post/](localhost:1313/post/), it behaves as expected and displays the articles in the `post` directory in a list format. However, when I go to [localhost:1313/new-section/](localhost:1313/new-section/), it says that I don't have any posts yet even though I have `article.md` under the `new-section` directory.

Another issue is that the `_index.md` files do not work as expected. The content in these files is not displayed on the list pages.

I believe my problem is similar to the one referenced in #16. It would be great if you could fix this issue since I really like this theme and would like to be able to use a functional version of it. If it helps, I believe [this theme](https://github.com/Shadow53/BluestNight) has this issue fixed.

**Comment by Vimux** [comment]
Thank you, I know about this problem. I'll fix it this weekend.

In addition to fix, need to create new blocks, CSS styles for them (`_index.md` content) and other stuff.

**Comment by Vimux** [comment]
@grenmester 

Done.
I need help with testing. If you find a bug, please let me know, otherwise close the issue.

**Comment by grenmester** [comment]
Thank you!
