### ISSUE TITLE
Add support to mermaid

### ISSUE THREAD

**Issue by BeTmAsTeR** [Vimux/Mainroad#170]
Adding support to [mermaid](https://mermaid-js.github.io/mermaid/#/) would be really useful to enable the creation of simple dagrams inside posts in a markdownish way.

This type of integration is already used in editor like https://stackedit.io/ and works really well

**Comment by Vimux** [comment]
Hi @BeTmAsTeR,

Each new third-party dependency increases complexity. No, I don't plan to add mermaid-js, at least not yet. Why not just use `customJS`? Any problems with this?

**Comment by BeTmAsTeR** [comment]
Implementing mermaid like you did with mathjax would allow to selectively turn it on or off depending on the article, choose the CDN and the lib options

**Comment by Vimux** [comment]
Yes, it can be useful. And No, I'm not going to support this because of complexity (as I said earlier).

MathJax as dependency does not mean that I accept any other dependency, just like JS code for a mobile menu does not mean that I accept any other JS code without very strong reasons.
