### ISSUE TITLE
Security-related pull requests

### ISSUE THREAD

**Issue by ludwa6** [Vimux/Mainroad#172]
As a non-technical (and happy :-) user of Mainroad theme, i've been wondering what to do with  emailed security alerts that i've received from notifications@github.com, saying things like this one received 2 days ago: 

   `Known high severity security vulnerability detected in mixin-deep < 1.3.2 defined in package-lock.json.`

That one -flagged as "high severity"-  triggered a pull request in my blog's repo from "dependabot," which seems to pass all those automated tests, so i'm wondering: should i just push the big green "merge pull request" button, and consider that problem solved?

Also: i now see an earlier pull request, generated by that same "dependabot" for a different issue:
  ` Bump eslint-utils from 1.3.1 to 1.4.3 in /themes/Mainroad`

The latter has been open since Oct 21 of last year, i now see (guess i should be more vigilant about these things!), so again i have to ask: should i just merge that pull request? And if so: does sequence matter, and should i do this one before the other (later) one?

(sorry for the n00b questions, but i need to be sure before i go and break something that's working so well as it stands!)

**Comment by Vimux** [comment]
Hello,

It depends. There's always some risk with making upgrades since changing code could imply an unexpected change. I don't know how you include and update Mainroad, what is your CI/CD process, etc.

In general terms:

1. You can't break Mainroad theme functionality if something going wrong with npm package updates, because there are no dependencies, only dev dependencies for code linting. So, yes, you can merge PR from Dependabot.
1. Until you don't initialize npm scripts from your repo with Mainroad somehow (on CI/CD runners or local machines), it doesn't affect you in terms of security.

**Comment by ludwa6** [comment]
Thanks, Vimux: though i don't understand much of what you said, i merged those two pull requests (in order received), trusting on your word that nothing would break -and indeed nothing did, AFAICT. 

Those two were easy, since dependabot took care of those pesky dependencies in its pull requests...  But i have in fact received other security alerts by email that did not result in a pull request.  So i have just (for the first time) checked my repo's Security tab, and found [this Security Alert](https://github.com/ludwa6/blog_rf1/network/alert/themes/Mainroad/package-lock.json/set-value/open) that suggests a certain remediation (appended below) on the file Mainroad/package-lock.json, which i'm not quite clear how i should do, if indeed i should (?) . Regarding this code snippet:

```
"dependencies": {
  "set-value": ">=2.0.1"
}
or…
"devDependencies": {
  "set-value": ">=2.0.1"
}
```
How should a non-programmer like me (bit of Python, more of R, but absolutely 0 of .json) interpret and (perhaps) act on this?  Regarding this package-lock.json file, should i insert that code somewhere in that huge list of dependencies, which starts right in after the opening line with "@babel/core" ... And goes on to include *many* instances of the string "set-value" , many of which appear set to version 2.0, and i would therefore guess should be reset to value 2.0.1... But i have no idea if it's a simple matter of running a "replace all" command, or rather doing this selectively, or...

OR (what would be immensely preferable for me :-), can i safely ignore all this?
