### ISSUE TITLE
Handle menu bar overflow

### ISSUE THREAD

**Issue by grenmester** [Vimux/Mainroad#18]
So I managed to overflow my menu bar while experimenting and this is what I see.

![image](https://cloud.githubusercontent.com/assets/13500910/26539638/2831790c-4480-11e7-817f-d6642f4abfd7.png)

What appears to have happened is that the menu bar has wrapped around. The red box near the top left is supposed to be an item in the menu bar. It would probably be nice to address this issue somehow.

**Comment by Vimux** [comment]
I'll check and see what I can do.

**Comment by Vimux** [comment]
@grenmester 

Please check and let me know that all menu items have (non-zero) titles. It seems that the menu items without the correct title cause error.

I am waiting for a confirmation.

**Comment by grenmester** [comment]
Ah yes, it seems that I have forgotten to set the title attribute. Once I set it, the issue was fixed.

**Comment by Vimux** [comment]
Anyway, I'll add an exception for menu items with zero titles.

**Comment by Vimux** [comment]
Now menu items without title are not displayed.  See: 151ac6d
