### ISSUE TITLE
package-lock.json Vulnerable

### ISSUE THREAD

**Issue by fervilber** [Vimux/Mainroad#185]
2 vulnerabilities are reported in **package-lock.json** 

1. upgrade kind-of to version 6.0.3 or later:
Vulnerable versions: < 6.0.3
Patched version: 6.0.3
ctorName in index.js in kind-of v6.0.2 allows external user input to overwrite certain internal attributes via a conflicting name, as demonstrated by 'constructor': {'name':'Symbol'}. Hence, a crafted payload can overwrite this builtin attribute to manipulate the type detection result.

2. minimist this as high severity:
Vulnerable versions: < 0.2.1
Patched version: 0.2.1
minimist before 1.2.2 could be tricked into adding or modifying properties of Object.prototype using a "constructor" or "proto" payload.

**Comment by Vimux** [comment]
https://github.com/Vimux/Mainroad/commit/ccff77dbec21d69f7ad9dc21b02bec8aa8f65312
