### ISSUE TITLE
Inline code and code blocks indistinguishable from normal text in summary view

### ISSUE THREAD

**Issue by cjerdonek** [Vimux/Mainroad#188]
Thank you for a great looking template.

I just started using this template and noticed that inline code and code blocks show up as normal text in the summary view. This can make the text look like gobbledygook when someone sees the summary, because all of the code is strung into one line and isn't distinguished from the text preceding and following. I'm attaching a couple screenshots of a very simple example (summary view and normal view).

<img width="511" alt="Screen Shot 2020-04-13 at 8 15 02 PM" src="https://user-images.githubusercontent.com/355822/79182822-a562d080-7dc4-11ea-93e8-d06cda3de7ae.png">
<img width="470" alt="Screen Shot 2020-04-13 at 8 21 34 PM" src="https://user-images.githubusercontent.com/355822/79182831-aa278480-7dc4-11ea-8bbb-5dd31992b62b.png">

**Comment by Vimux** [comment]
@cjerdonek,

This is how [automatic summary splitting](https://gohugo.io/content-management/summaries/#automatic-summary-splitting) works. Use manual splitting or add your own custom list layout for your site.

**Comment by cjerdonek** [comment]
Thanks. I also see there is a related issue in Hugo's tracker: https://github.com/gohugoio/hugo/issues/1503
