### ISSUE TITLE
my menu dont began form weight 1

### ISSUE THREAD

**Issue by mapleafly** [Vimux/Mainroad#190]
I created content\post\ccxt dir.   and created some md files.  all file set :
.....
menu: 
  side:
    name: CCXT dev book
    weight:  
.......
the weight from 1 to 5 for five files.  But,  when click menu "CCXT dev book", The first page dont open the md file  that be set weight 1.  i test some file. it seems not order by date too. 
help! I dont Solve the problem.

**Comment by Vimux** [comment]
I do not provide personal support. If it seems to you that the theme is not working correctly, please submit a new issue according to the [CONTRIBUTING guide → Reporting bugs](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md#reporting-bugs). Right now, I don't see any reproducing steps or even link to the example.
