### ISSUE TITLE
Custom social links failed

### ISSUE THREAD

**Issue by LovelyBuggies** [Vimux/Mainroad#200]
I want to add my YouTube channel to my social links. I referred to the demo `config.toml` in README, but it is broken and threw `partial "youtube.svg" not found`. It told me I have not put my SVG files to the right directory so it could not find. The fact is that I have put youtube.svg together with those svg files, so I think there is something wrong in [Params.widgets.social.custom]. Could anyone help?

**Comment by Vimux** [comment]
Hello,

> ...It told me I have not put my SVG files to the right directory so it could not find. The fact is that I have put youtube.svg together with those svg files...

It's not correct. In that case, you can't get such an error from Hugo. I recommend you check [this section](https://github.com/Vimux/Mainroad#social-widget-custom-links) **carefully**  and then try to test that feature again.

**Comment by LovelyBuggies** [comment]
Sorry for the bother, I see. Thanks!
