### ISSUE TITLE
facebook and telegram preview

### ISSUE THREAD

**Issue by halon176** [Vimux/Mainroad#202]
It may be just my misstake but no one link to the post that hugo genre shows a preview, neither on facebook nor with the telegram bot. Is it a feature that is not part of the theme?
thanks.

**Comment by halon176** [comment]
update:
facebook start to show preview image after i put in header of every post
`og_image:  "/media/img.jpg"`

o still have problems with telegram preview
P.S. i got   opengraph = true in config file

**Comment by Vimux** [comment]
> It may be just my misstake but no one link to the post that hugo genre shows a preview,

For such cases, Mainroad uses Hugo's internal templates, including Open Graph, Schema, and Twitter Cards. And this part works as expected (you can enable/disable params through config file). Everything else is up to you.

---

We use Github Issues to track bugs and proposing new features within this repository. It's not intended for any "it's not working for me, help" situations. I do not provide personal support in any kind.
