### ISSUE TITLE
Support for nested menu structure

### ISSUE THREAD

**Issue by ashishlahoti** [Vimux/Mainroad#203]
Require a support for nested menu structure based on config.toml configuration something like this:-
[menu]
  [[menu.main]]
    identifier = "menu1"
    name = "Menu1"
    title = "Menu1"
    url = "/"
    weight = 10
       [[menu.sumenu]]
           identifier = "submenu1"
           name = "SubMenu1"
           title = "SubMenu1"
           url = "/"

**Comment by Vimux** [comment]
No. #86, #101

**Comment by ashishlahoti** [comment]
Thanks. I understand that it is not supported at the moment. However, I've implemented the responsive nested menu structure on my own on top of hugo mainroad theme,  which might be helpful for others:

https://codingnconcepts.com/hugo/nested-menu-hugo/
