### ISSUE TITLE
search do not work (extra slash)

### ISSUE THREAD

**Issue by thierrybo** [Vimux/Mainroad#204]
Hi,

as you can see on the demo site https://themes.gohugo.io/theme/mainroad/
if you search pectoribus there is no result because the **search string is**
pectoribus site:https://themes.gohugo.io//theme/mainroad/
**instead of**
pectoribus site:https://themes.gohugo.io/theme/mainroad/

**Comment by Vimux** [comment]
This demo site not controlled by me, so I can't fix this. It's not my issue.

If you spent another two minutes, you would easily find another Mainroad demo that is controlled by me, where everything works as it should.
