### ISSUE TITLE
[Params.widgets.social] Not displaying anything in the sidebar

### ISSUE THREAD

**Issue by ctsdownloads** [Vimux/Mainroad#205]
- Running Hugo version hugo-0.72.0-2

- Usernames entered  for Twitter, Facebook, Etc for [Params.widgets.social] in my config.toml

- Running Hugo on my local host for testing and on Github pages.

- Add blocker is off. Tested with cleared cache on Chrome and Firefox.

- Adding usernames to the appropriate [Params.widgets.social] area gives me a successful:

```
Change of config file detected, rebuilding site.
2020-06-21 00:47:10.062 -0700
Rebuilt in 108 ms
```

After triple checking that there are no spaces or other obvious errors in my user names under [Params.widgets.social] I spent a few hours digging around trying to figure out what I may have missed.

It appears only Categories, tags and recent posts are displayed in the sidebar. 

I also checked the created index.html file in /public and it reflects the same in terms of widgets - only displays Categories, tags and recent posts in the html there for the /public directory.

I must be missing something somewhere? I'd genuinely appreciate the help.

Thanks

**Comment by kofemann** [comment]
Did you have enabled the widget itself?

```
[Params.sidebar]
  ...
  widgets = [..., "social"]

[Params.widgets.social]
  github = ...

```

**Comment by ctsdownloads** [comment]
I did not, but just now did. Can't believe I missed that. :)

Thanks again, great theme - really loving it.
