### ISSUE TITLE
How to list some latest articles behind the category?

### ISSUE THREAD

**Issue by diguage** [Vimux/Mainroad#216]
How to list some latest articles behind the category title at the category page?

![image](https://user-images.githubusercontent.com/2121467/85911291-01cb7d00-b857-11ea-8e62-30ecfcdf0a04.png)

My blog: <https://www.diguage.com/categories/>.

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**.

Closed.
