### ISSUE TITLE
thumbnail image maybe has a bug.

### ISSUE THREAD

**Issue by diguage** [Vimux/Mainroad#218]
This is a transparent PNG image. There is not a line in the image.

![image](https://user-images.githubusercontent.com/2121467/86387741-395a7f00-bcc6-11ea-881f-11bc948d35e4.png)

Example: https://www.diguage.com/.

**Comment by Vimux** [comment]
No, Mainroad does not contain such heading borders. It's your addition, so it's your problem.

Invalid.

**Comment by diguage** [comment]
Sorry, this is my mistake. I modified the style.
