### ISSUE TITLE
Menu Drop Down

### ISSUE THREAD

**Issue by cybersins** [Vimux/Mainroad#228]
The same theme when ported to my site - the MENU button is not working. It aligns/appears on the right but when clicked, does not drop-down.

Currently, the site is in development and testing.

![mainroad_issue](https://user-images.githubusercontent.com/8040258/91119160-257b3a00-e6c5-11ea-9d15-3a6bccb735ca.gif)

Hugo Version: v0.74.3/extended darwin/amd64

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes any reports like "how to do this or that", "everything is broken, help me", and so on. The issue tracker is the **preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

Closed and marked as invalid.
