### ISSUE TITLE
Order of the Menus

### ISSUE THREAD

**Issue by rjain15** [Vimux/Mainroad#230]
How is the order of the menu items decided? Is there a parameter in the menu which we can use to specify the order, or is it based on the date of the page?

**Comment by cybersins** [comment]
Hi rJain, 
I am using the weight to tailor the order of items in menus. Either in the theme `config` file or in the respective post directly. This gives me control of the ordering.

**Comment by cybersins** [comment]
Also, the default orders of menus are **alphabetical** or **date** :) See which one is on your side.

**Comment by rjain15** [comment]
Great the weight worked.
