### ISSUE TITLE
Change list title tag in summary.html to h2

### ISSUE THREAD

**Issue by damnsanc** [Vimux/Mainroad#234]
This improves seo.

**Comment by Vimux** [comment]
I have nothing against it in general, but I could be wrong about SEO, so let's give a week for discussion/feedback. If no one else argues against this change until the end of the next week, then I change this heading level.

**Comment by damnsanc** [comment]
No problem, thanks for the response


‫‪Vimux‬‏ <‪notifications@github.com‬‏> در تاریخ پنجشنبه ۱۰ سپتامبر ۲۰۲۰
ساعت ۱۸:۳۲ نوشت:‬
