### ISSUE TITLE
Hugo ≥0.76.* i18n breaks authorbox_name string

### ISSUE THREAD

**Issue by Vimux** [Vimux/Mainroad#237]
After upgrading to Hugo 0.76.*, the `authorbox_name` i18n string stops working correctly. 

### Hugo version

<pre>
$ hugo version
Hugo Static Site Generator v0.76.5/extended darwin/amd64 BuildDate: unknown
</pre>

### Theme is up to date?
**Yes**. https://github.com/Vimux/Mainroad/commit/8c2da72f92947e0bda55eacce1a70df8c3296ba5

### Expected behavior

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/21033483/96142450-19934380-0ed0-11eb-949f-9a4fdff436f0.png" alt="Screenshot without bug">
</details>

### Current behavior

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/21033483/96141804-60346e00-0ecf-11eb-8fbf-918ce9ffb3ae.png" alt="Screenshot with bug demonstration">
</details>

### Problem

exampleSite demo build log shows the following warning messages since bumping to Hugo 0.76.*:

```
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
WARN 2020/10/12 13:40:31 Failed to get translated string for language "en" and ID "authorbox_name": template: :1:9: executing "" at <.Count>: can't evaluate field Count in type string
```

As a result, i18n string (`authorbox_name`)  does not work as before.

### Steps to reproduce

**Prerequisites**: git, hugo 0.76.* 

1. Clone this repository and cd in the exampleSite dir

    ```bash
    git clone https://github.com/vimux/mainroad.git
    cd mainroad/exampleSite/
    ```

1. Run Hugo server with the following command:

    ```bash
    hugo server --themesDir ../..
    ```

1. Visit http://localhost:1313/post/hugoisforlovers/ in your browser and scroll to the bottom of the page.

---

https://github.com/gohugoio/hugo/issues/7822

**Comment by yuqingc** [comment]
Is there a way to fix the authorbox's display temporarily for those who use Mianroad before this issue is fixed?

**Comment by Vimux** [comment]
> Is there a compromising way to fix the authorbox's display temporarily for those who use Mianroad before this issue is fixed?

I don't have time to investigate this problem (yet). Options:

1) Don't upgrade Hugo just because, especially without testing. You will avoid this and other problems in future.
2) If you want to use Hugo ≥0.76, you can override specific i18n key-value without touching whole theme's i18n. [Lookup order](https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules). It's not ideal, but...

    + Add `i18n/en.yaml` within site's root:

    ```yaml
    # https://github.com/vimux/mainroad/issues/237
    - id: authorbox_name
      translation: "About {{ . }}"
    ```

     Hugo merge this particular key-value. If you use other or multiple languages, you should make similar according changes.

**Comment by mcdragonsi** [comment]
I am a bit lost. Is this issue fixed and if so, how do I apply it to Mainroad?

**Comment by arashThr** [comment]
@mcdragonsi Make sure you're on master and you've pulled the latest changes. Then, if you have custom translations file, change `{{ .Count }}` in it to `{{ .Name }}`
