### ISSUE TITLE
Support for menuTitle?

### ISSUE THREAD

**Issue by beedaddy** [Vimux/Mainroad#238]
Perhaps I miss something, but when I want to have a different title in the menu than in the page, can't I use menuTitle?
For example, the page title should be "Install on Linux" but the menu title should be "Linux". Is that supported?
```
---
title: "Install on Linux"
menuTitle: "Linux"
---
```
This doesn't seem to work for me (but I'm a newbie).

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
