### ISSUE TITLE
Question: How do I change the display order of categories in the Category widget?

### ISSUE THREAD

**Issue by riku22** [Vimux/Mainroad#239]
Hello.

I want to change the display order of the categories displayed in the category widget.
For example, if I have the following categories:

```
CategoryA
CategoryB
CategoryC
CategoryD
```

I want to display this in any order as shown below.

```
CategoryC
CategoryB
CategoryA
CategoryD
```

How can I do this?
The environment is Hugo 0.76.5.

Best regards.

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
