### ISSUE TITLE
No "read more" text on the read more button

### ISSUE THREAD

**Issue by branchus** [Vimux/Mainroad#246]
Hi
nice theme, really like it.

after i enabled the readmore, can only see a little black button, but no "read more" or similar on the button

any solutions?
Thanks

**Comment by Vimux** [comment]
1. [CONTRIBUTING.md#general-requirements](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md#general-requirements)
2. [CONTRIBUTING.md#reporting-bugs](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md#reporting-bugs)

---

**Closed and marked as invalid.**
