### ISSUE TITLE
Image files not loading with HTML

### ISSUE THREAD

**Issue by dbclinton** [Vimux/Mainroad#248]
Hi,
I've used your Mainroad theme for a couple of projects and I'm very happy with it. Thanks!
I'm having some trouble, however. My markdown files reference .png images in the same directory. They're all there together in content/docs/
But when Hugo builds the site, it creates individual directories for each of the new HTML files, but leaves all the images in public/docs/ 
But the HTML code is still looking for image files locally. That means the images won't load unless I go in and edit things manually. If it's helpful, you can see [the site here](http://datasite.bootstrap-it.com/) - I manually moved the images into the HTML file directories for this version.
Is this a theme issue or something funny with Hugo (or a mistake I'm making)?
```
$ hugo version
Hugo Static Site Generator v0.80.0 linux/amd64 BuildDate: 2020-12-31T20:00:21Z
```
Thanks,

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
