### ISSUE TITLE
printf not available in the theme's minimum hugo version

### ISSUE THREAD

**Issue by andytson** [Vimux/Mainroad#25]
printf, used in #21 isn't available in Hugo 0.19, which is the theme's minimum version. It was introduced in Hugo 0.20 https://github.com/spf13/hugo/commit/45b9d7223a8098f3c19871ec695c79384bc40871

The code affected is https://github.com/Vimux/Mainroad/blob/master/layouts/_default/list.html#L26

options are to either:

1. update the minimum version to 0.20
2. update the code to use range and if conditions to add the comma's, content/, and "and". Note this would not be pretty
3. use a simpler formatting, not using natural language, or structured differently like

```
As posts are added in the content subfolders (blog, news) ...
```

What do you think?

**Comment by Vimux** [comment]
I prefer the first option.

On the other hand, how about `.Hugo.Version` variable? For 0.19 we can show a message like from option 3. Not exactly this but similar.

 I can't verify that it works yet. Need to try.

**Comment by Vimux** [comment]
Hugo 0.22 released. My experiments partially failed (Couldn't catch correctly versions with 2 divider dots, like 0.20.2).  So I decided to bump Hugo min version to 0.20
