### ISSUE TITLE
showTitle front matter

### ISSUE THREAD

**Issue by zhiqiyu** [Vimux/Mainroad#250]
There was once a front matter named `showTitle` that conveniently hide the title of a post, but it is no longer there. Is there a reason why it is removed? It could be useful.

**Comment by Vimux** [comment]
> There was once a front matter named `showTitle` that conveniently hide the title of a post, but it is no longer there.

There is no such parameter and never has been.

> Is there a reason why it is removed?

If you are sure that it was here, then it will be easy to show in which commit it happened, right?

I close this issue.

**Comment by zhiqiyu** [comment]
Oops, sorry, it seems that I may have manually added this front matter myself a long time ago without using Git to track changes. Sorry for the inconvenience and thanks for this wonderful theme!
