### ISSUE TITLE
alt for logo.png

### ISSUE THREAD

**Issue by wishart66** [Vimux/Mainroad#256]
Hi

I really like your theme and I use it for [](https://glasgowtales.com) and it works perfectly. https://glasgowtales.com

Just one minor issue: when I run a SEO checker image = "/img/logo.png" does not have the ALT attribute. I've tried various methods to add it in logo.html, but none work. I've looked at logo.html and tried various ways to add ALT.

If you check the element on index.html for my page, you'll see that I have ALT after TITLE, but SEO checkers don't pick that up. Should I try to add the ALT manually to the index.html in the public folder before uploading?

Just want to point out that I don't know much about programming but know a little HTML.

Thanks
Wishart.

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
