### ISSUE TITLE
Where's the content for the "Standard Demo"?

### ISSUE THREAD

**Issue by shileiphys** [Vimux/Mainroad#257]
Hi, the exampleSite only contains the "Fast Demo" posts, I'd like to try those under "Stand Demo" too. Thanks

**Comment by shileiphys** [comment]
and <sub> and <sup> don't seem to work either.

**Comment by Vimux** [comment]
https://github.com/gohugoio/HugoBasicExample

**Comment by shileiphys** [comment]
Hi, in the standard demo, the sub and sup are not working.
