### ISSUE TITLE
Add Indonesian Translation

### ISSUE THREAD

**Issue by atdx** [Vimux/Mainroad#258]
Add Indonesian Translation

**Comment by atdx** [comment]
https://github.com/atdx/Mainroad/blob/master/i18n/id.yaml

**Comment by Vimux** [comment]
Hi.

Could you please make a PR request (+ based on dedicated, not your master branch)?

**Comment by Vimux** [comment]
Just a friendly reminder, if you still want to add this translation, you need to open a [Pull Request](https://github.com/Vimux/Mainroad/pulls), otherwise, I will close this issue after a while (2 weeks or so).

**Comment by atdx** [comment]
please wait a moment, I'm not familiar with linux and git, I tried and failed, I'll try again soon.
