### ISSUE TITLE
Generate FLoC opt-ins

### ISSUE THREAD

**Issue by peschkaj** [Vimux/Mainroad#266]
Based on https://make.wordpress.org/core/2021/04/18/proposal-treat-floc-as-a-security-concern/ and other published concerns, it seems wise to treat FLoC as something that site owners should explicitly enable.

**Comment by Vimux** [comment]
Hi,

could you please give me more data about how this should work?

**Comment by peschkaj** [comment]
My thought was that unless the site owner opts into FLoC by setting `.Site.Params.floc_optin` to `true`, this would add the FLoC opt-out meta tag (`<meta http-equiv="Permissions-Policy" content="interest-cohort=()"/>`).

I have an implementation at https://github.com/peschkaj/Mainroad/commit/f649c2feb9ef7c015f1eacc65b3e6c2c98e98826, but am happy to re-implement a different way.

**Comment by Vimux** [comment]
My question is not even about our specific implementation right now, but how does this magical thing work in general? Where can I read what happens when I add this (`<meta http-equiv="Permissions-Policy" content="interest-cohort=()"/>`)? On which side this tag controlled? I want to get (minimal) technical analysis about FLoC opt-in/opt-out, how it works, before adding something like this to my project.

**Comment by Vimux** [comment]
As always, I am ready to listen to everyone's opinions.

**Comment by peschkaj** [comment]
In short, FLoC bucketizes users into cohorts based on sites they visit without the user's consent.

From https://github.com/WICG/floc, 
> A FLoC cohort is a short name that is shared by a large number (thousands) of people, derived by the browser from its user’s browsing history. The browser updates the cohort over time as its user traverses the web. The value is made available to websites via a new JavaScript API:
> 
>     cohort = await document.interestCohort();
>     url = new URL("https://ads.example/getCreative");
>     url.searchParams.append("cohort", cohort);
>     creative = await fetch(url);
>
> The browser uses machine learning algorithms to develop a cohort based on the sites that an individual visits. The algorithms might be based on the URLs of the visited sites, on the content of those pages, or other factors. The central idea is that these input features to the algorithm, including the web history, are kept local on the browser and are not uploaded elsewhere — the browser only exposes the generated cohort. The browser ensures that cohorts are well distributed, so that each represents thousands of people. The browser may further leverage other anonymization methods, such as differential privacy. The number of cohorts should be small, to reinforce that they cannot carry detailed information — short cohort names ("43A7") can help make that clear.

EFF has a write up about why [FLoC is a terrible idea](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea).

By setting the cohort to an empty string, this meta tag does the most we can do via HTML (at the moment) to opt users out of FLoC. There are other methods to [opt users out of FLoC via HTTP headers](https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network), but they rely on having access to the underlying website. The more simple static site options (e.g., GitHub Pages and Azure Static Sites) can't take advantage of the HTTP header approach, so the meta tag is a good fallback.

**Comment by Vimux** [comment]
> By setting the cohort to an empty string, this meta tag does the most we can do via HTML (at the moment) to opt users out of FLoC.

I tried to sort this out last night. I didn't even find direct mention that this tag works. Could you please point out the exact place where this stated? On contrary, [this webpage](https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network#github-pages) from you says the opposite thing, I guess.

**Comment by peschkaj** [comment]
> On contrary, this webpage from you says the opposite thing, I guess.

Oof, I had seen that when it was originally written and grabbed the URL from my history. I didn't notice that it had been updated since. Looks like the proposed approach isn't feasible after all.

**Comment by peschkaj** [comment]
Closing since I don't think this is possible with meta tags.
