### ISSUE TITLE
Seo issue in tags and categories

### ISSUE THREAD

**Issue by khannzxc** [Vimux/Mainroad#272]
Thanks for this awesome theme. Can we increase SEO performance further as it has some issue.
For example it has no meta description on the tags and categories page
Such as

![seo222](https://user-images.githubusercontent.com/40522970/126514747-e17ce85e-d349-4f42-ab3d-df57ed167378.JPG)

And duplicate page title 

![seo111](https://user-images.githubusercontent.com/40522970/126513981-0a80819c-5e88-4885-8ffe-94a4819d43b1.JPG)

we can check SEO with Sitechecker
[https://sitechecker.pro](url)

**Comment by Vimux** [comment]
> For example it has no meta description on the tags and categories page

Have you tried adding some meta description text for these pages?

**Comment by khannzxc** [comment]
yeah but that was a sort of manual method. For these types of URL
```https://mainroad-demo.netlify.app/tags/```
not ```https://mainroad-demo.netlify.app/tags/basic-elements/```

through this code
```{{ if .Data.Plural }} <meta name="description" content="{{$.Param "description2"}}"> {{else}} <meta name="description" content="{{ $.Param "description" }}"```

I just check the site with the SEO checker pro website. and searching for some improvements

**Comment by Vimux** [comment]
No, I don't plan to change how this works, especially this way.

Closed.
