### ISSUE TITLE
How to Deploy on the Netifly

### ISSUE THREAD

**Issue by chaitanyasaxena246** [Vimux/Mainroad#278]
Hello

Will you please guide me how we can deploy this site to the netifly

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
