### ISSUE TITLE
Help with menus

### ISSUE THREAD

**Issue by vijaypanchalr3** [Vimux/Mainroad#279]
how to create menus like, All of the contents, Blogs, About

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
