### ISSUE TITLE
controlling the website icon on browser tab

### ISSUE THREAD

**Issue by aninchat** [Vimux/Mainroad#280]
Hi, I'm unable to find out how the website icon on the browser tab is used in the theme and how it can be changed. It looks like it is pulling either the apple-touch-icon.jpg or the favicon.ico image, but I cannot find from where. 

Can you please help in clarifying how this can be modified?

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. This includes reports like "how to do this or that", "everything is broken, help me", "I changed something and now it doesn't work", and so on. **The issue tracker is the preferred channel for bug reports and feature requests which comply with our contributing rules**, nothing more. I do not provide personal tech support.

**Closed and marked as invalid.**
