### ISSUE TITLE
Add support for "series" Front Matter

### ISSUE THREAD

**Issue by greg-hellings** [Vimux/Mainroad#282]
Add support to the theme for the "series" front matter in a post's page to link to other posts in the series as they are written.

**Comment by Vimux** [comment]
No, I don't plan to add such functionality.

I closed this issue because I don't plan to address it in the foreseeable future.

**Comment by greg-hellings** [comment]
Is this because it is an unwanted feature, or would you be willing to accept a PR that implements this? I'm happy to do the work to have this in the theme if you're just not interested in doing the implementation.

**Comment by Vimux** [comment]
@greg-hellings,

No, I don't plan to add such a feature anyway. Mainroad must remain with the minimum number of additional features, and I believe this is out of the scope of our project.
