### ISSUE TITLE
Inline Mathjax does not work

### ISSUE THREAD

**Issue by bjdaig** [Vimux/Mainroad#284]
Markdown such as:
`A profile shows when $ g = g_{max}/2, \ z = 1.3x_{1/2} $, where $ x_{1/2} $ is the half width of the profile at $ g_{max}/2 $.`
will not render.  VS Code will display it properly but Hugo will not render it using the Mainstream template.  Is there a way to add additional Mathjax parameters perhaps.  If VS Code renders it properly, then the parameters should already be set. The \( \) optional sytax doesn't work in VS Code or Mainstream.

**Comment by Vimux** [comment]
We don't provide support for additional MathJax configs by default. If you want to use single-dollar delimiters for inline math, you need to activate this feature somehow. For example, copy (`./themes/mainroad/layouts/partials/mathjax.html` `./layouts/partials/mathjax.html`) and modify the `mathjax.html` partial.

http://docs.mathjax.org/en/latest/upgrading/earlier/upgrade.html?highlight=inline#combined-configurations

---

Duplicate:
https://github.com/Vimux/Mainroad/issues/207
https://github.com/Vimux/Mainroad/issues/177
