### ISSUE TITLE
Ability to Turn Off Disqus for Certain Pages?

### ISSUE THREAD

**Issue by oneleaftea** [Vimux/Mainroad#30]
Awesome theme! In many other themes, the option is there to turn off comments for certain pages/posts by adding a "comments = false" in the frontmatter. This would be great in, for instance, the about.md page. Any possibility to add this feature?
Thanks!

**Comment by Vimux** [comment]
@oneleaftea,
Mainroad supports ability to turn off Disqus for certain pages: use parameter `disable_comments = true`.

**Comment by oneleaftea** [comment]
Ah, thanks! Just tried it and worked!
