### ISSUE TITLE
Math render

### ISSUE THREAD

**Issue by opoyc** [Vimux/Mainroad#31]
Hi
I am having problems to visualize math in latex into your theme. It is very good by the way, thanks!

**Comment by Vimux** [comment]
Hi, @opoyc.

Could you provide more information about problem?
Also, could you show an example of hugo theme ([from official hugo themes repository](https://github.com/gohugoio/hugoThemes)) where math render works correctly?

**Comment by opoyc** [comment]
I'm working with blogdown in R. And after reviewing the package's book I found that I can modify the foot.html file to include the javascript for MathJax rendering. Now it is working properly

Thanks!
