### ISSUE TITLE
Active menu class is broken

### ISSUE THREAD

**Issue by Jean85** [Vimux/Mainroad#314]
I just upgraded from Hugo 0.80 to 0.111.1, and pulled this theme (from b1d3ae0 to e9bce51) and I noticed, on the deployed site, that the `menu__item--active` class was gone in multiple pages.

This means that the menu element is no longer highlighted when that's the current page.

This is the offending piece of code: https://github.com/Vimux/Mainroad/blob/e9bce51b09d8a48fd66808f6d5382074c9584c30/layouts/partials/menu.html#L7-L18

It didn't change due to my pull, so I don't know why it stopped working.

**Comment by Jean85** [comment]
I noticed that the Hugo docs report some changes about it in 0.86: https://gohugo.io/functions/hasmenucurrent/
Also, the example in the docs seems coherent with that we do here: https://gohugo.io/templates/menu-templates/

**Comment by Vimux** [comment]
> I just upgraded from Hugo 0.80 to 0.111.1

Sounds like a "**VERY GOOD PRACTICE**".

> I noticed that the Hugo docs report some changes about it in 0.86: https://gohugo.io/functions/hasmenucurrent/

Hugo 0.86.0 сhangelog?

**Comment by Jean85** [comment]
> Hugo 0.86.0 сhangelog?

https://github.com/gohugoio/hugo/releases/tag/v0.86.0

**Comment by Vimux** [comment]
> https://github.com/gohugoio/hugo/releases/tag/v0.86.0

Have you even tried reading the changelog?

**Comment by Jean85** [comment]
Yes I did, but it appears that I misunderstood it.

I've now fixed it by adding the `pageRef` attribute to each menu entry. Sorry for the misunderstanding.
