### ISSUE TITLE
Math formulas/equations not displaying properly on blog.

### ISSUE THREAD

**Issue by kelvinmmuia** [Vimux/Mainroad#326]
Hey there,

I have an issue with Mathjax support for the awesome Mainroad theme. 

Currently, the following Math formulas do not display properly on my blog, but they do display well in Rstudio. What could be the issue and how can I remedy this?
- $\mathcal{N}(\mu, \sigma^2)$
- $\mathcal{N}(0, 1)$
- $f(x) = \frac{1}{b - a}$
- $X \sim \text{Exponential}(\lambda)$
- $f(x;p) = p^x \cdot (1 - p)^{1 - x}$
-  $x$
etc.

Thank you in advance.

**Comment by Vimux** [comment]
Duplicate #207, #284?
