### ISSUE TITLE
Google Font Page Speed issue

### ISSUE THREAD

**Issue by radenkozec** [Vimux/Mainroad#327]
Hi. Great theme.
I just want to ask when I run test for Google Page Speed it complains about Google Fonts in your theme:
"Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading."
"Eliminate render-blocking resources"

Is it smart to try preload font or something similar and why have you not already implemented this?
https://stackoverflow.com/questions/45983301/google-pagespeed-eliminate-render-blocking-resources-above-the-fold-caused-fro

**Comment by Vimux** [comment]
Why not just add a `&display=swap` suffix for your `googleFontsLink` parameter?

**Comment by radenkozec** [comment]
I have put this in Hugo.toml:
```
[Params]
   googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap" # Load Google Fonts
```

After that when I run Google Page Speed I get this error for font:
"Eliminate render-blocking resources" 

But this first error disappears. So this help for one error but how to solve second error?

**Comment by Vimux** [comment]
It seems pretty obvious. Google fonts are added to the page as CSS rules to define each specified font. By definition, this is a render-blocking resource. That's how all Google fonts are usually loaded.

If you want to fix the "error" without masking it, you should not use any web fonts, i.e., use either local fonts or the system font stack.
