### ISSUE TITLE
Change minimum supported version

### ISSUE THREAD

**Issue by bwc69151** [Vimux/Mainroad#328]
You mention v.0.87 is required in a recent PR. Change the values here and in the readme file
https://github.com/Vimux/Mainroad/blob/master/theme.toml

**Comment by Vimux** [comment]
Show me exactly how support for Hugo 0.48.0 broke with [this commit](https://github.com/Vimux/Mainroad/commit/903ae2d032c6b1299ee259822919b4f92f05c2cf). I suggest you carefully read the commit message and the corresponding PR before. It seems that I write all these messages for myself. 🤦‍♂️

Marked as invalid.

**Comment by bwc69151** [comment]
> Show me exactly how support for Hugo 0.48 broke with [this commit](https://github.com/Vimux/Mainroad/commit/903ae2d032c6b1299ee259822919b4f92f05c2cf). I suggest you carefully read the commit message and the corresponding PR before. It seems that I write all these messages for myself. 🤦‍♂️
> 
> Marked as invalid.

I don't actually use this theme. I have my own design based on MH Magazine lite that I ported to Hugo years ago.
