### ISSUE TITLE
Removing the favicon

### ISSUE THREAD

**Issue by ragonneau** [Vimux/Mainroad#330]
Hi,

First of all, thank you very much for the theme. I wonder whether it was possible to easily remove the favicon? I tried to copy `layouts/_default/baseof.html` into my own project, modifying it to remove the corresponding line, but this did not have any effect (although the generated HTML did change).

Do you have any idea?

Cheers,
Tom.

**Comment by Vimux** [comment]
That's because browsers always look for the favicon.ico file even if you don't specify it within your HTML. Search keywords for Google: "favicon 404".
