### ISSUE TITLE
[Feature] Provide theme as module

### ISSUE THREAD

**Issue by MTecknology** [Vimux/Mainroad#334]
I am trying to provide "aamod" as a hugo module. However, this was built as a "subtheme" of mainroad. This means that mainroad would still need to be included a git submodule.

Can you consider releasing Mainroad as a hugo module?

**Comment by Vimux** [comment]
I have no plans to change that at the moment. Partly discussed in #292.

**Comment by MTecknology** [comment]
Interesting ... that PR was closed saying that an issue should be opened for discussion, and then a ticket opened for discussion was closed as "not interested." That seems unfortunate, but I certainly appreciate the quick and complete response.

From my own personal perspective, the module approach is easier to support and cleaner to implement, but also more confusing to maintain because of inadequate developer-focused documentation. That approach also "highly encourages" semver versioning, which is something a tremendous number of golang-related projects are in desperate need of.
