### ISSUE TITLE
Add support for Mouthful comments

### ISSUE THREAD

**Issue by apogorzelska** [Vimux/Mainroad#335]
Are there any plans to make it possible to use [Mouthful](https://github.com/vkuznecovas/mouthful)-based comments instead of Disqus?

**Comment by Vimux** [comment]
I have no plans to add and maintain alternative comments. It's not worth complicating our comments.html to support multiple systems. However, no one is forbidding the use of other commenting systems. Such systems require a modified comments.html (+ custom JS?).

See #253.
