### ISSUE TITLE
After deployment, the sidebar cannot be displayed

### ISSUE THREAD

**Issue by hieroglyphicss** [Vimux/Mainroad#338]
I customized a component and filled in the information, and everything was previewed locally as normal, but after being deployed to Vercel, I couldn't see it anymore. The same goes for using cloudflare pages.
![](https://s1.ax1x.com/2023/08/18/pP3iHO0.png)
![](https://s1.ax1x.com/2023/08/18/pP3ivY4.png)
I am using Chrome, version 115.0.5790.171 (official version) (64 bit)

**Comment by Vimux** [comment]
**I do not provide free personal technical support.** 

As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support**. This includes any reports like “how to do this or that”; “everything broken, help me”; “I changed something, it doesn't work anymore”; “It's not a personal issue, I just want to ask how X or Y works”; “I forked your repository, then something broken, fix this immediately” and so on.

**The issue tracker is the preferred channel for bug reports, feature requests, and discussions that comply with [our contributing rules](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md)**, nothing more.

**Closed and marked as invalid.**
