### ISSUE TITLE
ability to remove pager from single pages

### ISSUE THREAD

**Issue by upcomingtradera** [Vimux/Mainroad#342]
This is a short code
could we add a param to allow pager to be displayed on single pages?
it's as simple as updating the current hugo template partial from:

```go
{{- if .Param "pager" }}
{{- if or (.PrevInSection) (.NextInSection) }}
```
to something like this
```go
{{- if .Param "pager" }}
{{- if and (or (.PrevInSection) (.NextInSection)) (eq .Section "posts") }}
```

you could expose a switch that we can configure in the config.toml to show both, none, pages or all or something like that?

Is that a change that you can upstream?

**Comment by Vimux** [comment]
> Is that a change that you can upstream?

No.

Mainroad already allows you to control the pager globally or by specific page, that's enough.
