### ISSUE TITLE
error calling partial: partial "youtube.svg" not found

### ISSUE THREAD

**Issue by calalloo** [Vimux/Mainroad#346]
Create the `youtube.svg` icon

**Comment by Vimux** [comment]
Rather than mindlessly copying the example config from the README (which clearly states that you should not), I suggest that you read the README first. Duplicate #224.

**Comment by calalloo** [comment]
> Rather than mindlessly copying the example config from the README

No need to be rude dude! You are the one who put that option there without including the icon or mentioning a user needs to include one in the partials...I was going to use the theme for a friend's site, but with this attitude I'd rather go with another theme!

**Comment by Vimux** [comment]
> No need to be rude dude! You are the one who put that option there without including the icon or mentioning a user needs to include one in the partials...

I'm not. To recap: README instructions ignored, issue not following CONTRIBUTING guidelines, no reproducible steps, just an imperative command to "create the youtube.svg icon". Second comment accuses me of including the option without mentioning that a user needs to place an icon. Incorrect, our documentation contains all the necessary information. It's disrespectful to me and to the community. Farewell.
