### ISSUE TITLE
Recent Posts: Not Consistent and Unable to Correct

### ISSUE THREAD

**Issue by imagelessthought** [Vimux/Mainroad#353]
Here is my repo: https://github.com/imagelessthought/imageless-mainroad

The issue I am having is that there are two folders in content wit the same layouts and front matter.  One is included in the recent posts and the other is not.  I do not want either included but cannot seem to control that so I am hoping someone can help identify the issue.

The two folders under content/ are "departments"  and "services".  Services works fine - they do not show up in the recent posts.  Departments do and I am unable to detemrine why.

I have searched through everything I can think of but canot resolve.

Any ideas?  Is this a bug, it seems like it, or is there a way to resolve this?  Thanks.

**Comment by Vimux** [comment]
- https://gohugo.io/methods/site/mainsections/
- https://github.com/Vimux/Mainroad#configtoml-example

**Comment by imagelessthought** [comment]
Just found that!  

[Params]
mainSections = [“posts”] # Specify section pages to show on home page and the “Recent articles” widget

It would be nice if these were not lumped together in one var: you may want them to appear in recent posts section but not shown on the homepage.

If that is possible by another means - please share. Thanks.

**Comment by imagelessthought** [comment]
I found a workaround by adding this line to /context/_index.md

.list__item { display: none; }
This hides them on the homepage but does not interfere with them appearing in recent on the sidebar.
