### ISSUE TITLE
CSS doesn't show <code>

### ISSUE THREAD

**Issue by d3zd3z** [Vimux/Mainroad#36]
The CSS for Mainroad doesn't have any rules to indicate Code blocks (such as `code` in Markdown).  This makes small quoted snippets blend in with the quoted text.

**Comment by talios** [comment]
I include:

```
code {
 font-family: "Consolas", Courier New, Courier, monospace;
 color: #000;
 background: #f5f5f5;
 white-space: pre-wrap;
 white-space: -o-pre-wrap;
 white-space: -moz-pre-wrap;
 white-space: -webkit-pre-wrap;
}
```

in my local Mainroad based site. Looks fairly reasonable.

**Comment by Vimux** [comment]
Thank you. I add styles for <code>.
