### ISSUE TITLE
Inserting the search widget at the top of the home page (content/_index.md)

### ISSUE THREAD

**Issue by imagelessthought** [Vimux/Mainroad#361]
On a mobile device the search bar appears under the page content along with the rest of the sidebar widgets.  I wanted to move just the search widget to the top.

Below is the partial I created for it and the code to insert it into a template.  It works on every page except for the one I need it to: the home page created by content/_index.md.  I assume there is something that by design blocks inserting a partial in this manner on this page but I cannot determine what is blocking it or how to disable that.  

Any help would be appreciated.  Thanks.

<div class="mobile-search-container">
    {{ partial "widgets/search.html" . }}
</div>
<script>
    summaryInclude=60;
    var fuseOptions = {
      shouldSort: true,
      includeMatches: true,
      threshold: 0.0,
      tokenize:true,
      location: 0,
      distance: 100,
      maxPatternLength: 32,
      minMatchCharLength: 1,
      keys: [
        {name:"title",weight:0.8},
        {name:"contents",weight:0.5},
        {name:"tags",weight:0.3},
        {name:"categories",weight:0.3}
      ]
    };
    
    var searchQuery = param("s");
    if(searchQuery){
      $("#search-query").val(searchQuery);
      executeSearch(searchQuery);
    }else {
      $('#search-results').append("<p>Please enter a word or phrase above</p>");
    }
    
    function executeSearch(searchQuery){
      $.getJSON(baseurlSub + "index.json", function(data) {
        var pages = data;
        var fuse = new Fuse(pages, fuseOptions);
        var result = fuse.search(searchQuery);
        console.log({"matches":result});
        if(result.length > 0){
          populateResults(result);
        }else{
          $('#search-results').append("<p>No matches found</p>");
        }
      });
    }
    
    function populateResults(result){
      $.each(result,function(key,value){
        var contents= value.item.contents;
        var snippet = "";
        var snippetHighlights=[];
        var tags =[];
        if( fuseOptions.tokenize ){
          snippetHighlights.push(searchQuery);
        }else{
          $.each(value.matches,function(matchKey,mvalue){
            if(mvalue.key == "tags" || mvalue.key == "categories" ){
              snippetHighlights.push(mvalue.value);
            }else if(mvalue.key == "contents"){
              start = mvalue.indices[0][0]-summaryInclude>0?mvalue.indices[0][0]-summaryInclude:0;
              end = mvalue.indices[0][1]+summaryInclude<contents.length?mvalue.indices[0][1]+summaryInclude:contents.length;
              snippet += contents.substring(start,end);
              snippetHighlights.push(mvalue.value.substring(mvalue.indices[0][0],mvalue.indices[0][1]-mvalue.indices[0][0]+1));
            }
          });
        }
    
        if(snippet.length<1){
          snippet += contents.substring(0,summaryInclude*2);
        }
        //pull template from hugo templarte definition
        var templateDefinition = $('#search-result-template').html();
        //replace values
        var output = render(templateDefinition,{key:key,title:value.item.title,link:value.item.permalink,tags:value.item.tags,categories:value.item.categories,snippet:snippet});
        $('#search-results').append(output);
    
        $.each(snippetHighlights,function(snipkey,snipvalue){
          $("#summary-"+key).mark(snipvalue);
        });
    
      });
    }
    
    function param(name) {
        return decodeURIComponent((location.search.split(name + '=')[1] || '').split('&')[0]).replace(/\+/g, ' ');
    }
    
    function render(templateString, data) {
      var conditionalMatches,conditionalPattern,copy;
      conditionalPattern = /\$\{\s*isset ([a-zA-Z]*) \s*\}(.*)\$\{\s*end\s*}/g;
      //since loop below depends on re.lastInxdex, we use a copy to capture any manipulations whilst inside the loop
      copy = templateString;
      while ((conditionalMatches = conditionalPattern.exec(templateString)) !== null) {
        if(data[conditionalMatches[1]]){
          //valid key, remove conditionals, leave contents.
          copy = copy.replace(conditionalMatches[0],conditionalMatches[2]);
        }else{
          //not valid, remove entire section
          copy = copy.replace(conditionalMatches[0],'');
        }
      }
      templateString = copy;
      //now any conditionals removed we can do simple substitution
      var key, find, re;
      for (key in data) {
        find = '\\$\\{\\s*' + key + '\\s*\\}';
        re = new RegExp(find, 'g');
        templateString = templateString.replace(re, data[key]);
      }
      return templateString;
    }
    </script>

- Insert into layout:
{{ partial "mobile-search.html" . }}

**Comment by imagelessthought** [comment]
Changing the content/_index.md to index.md allowed the partial to be added as I needed but now the menu doesn't work.  So it is definately something related to how the content/_index.md file alone is treated.

It also cloud be the primary div, as partials are included in the sidebar.

**Comment by Vimux** [comment]
**I do not provide free personal technical support.** 

As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support**. This includes any reports like “how to do this or that”; “everything broken, help me”; “I changed something, it doesn't work anymore”; “It's not a personal issue, I just want to ask how X or Y works”; “I forked your repository, then something broken, fix this immediately” and so on. **The issue tracker is the preferred channel for bug reports, feature requests, and discussions that comply with [our contributing rules](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md)**, nothing more.

**Comment by imagelessthought** [comment]
Found the issue: the index.html template is located in \layouts and not layouts\_default\ with the other templates. Once I added the partial there it worked fine.  Not sure where it is documented in the Hugo docs - I didn't see it.  So I tried creating one in _defaults, which was ignored.  So it seemed like the something wasn't working as intended.

**Comment by jmooring** [comment]
<https://gohugo.io/templates/lookup-order/#home-page>
