### ISSUE TITLE
RSS content is not generated

### ISSUE THREAD

**Issue by vguhesan** [Vimux/Mainroad#37]
Looking to see how to generate RSS content with this theme. Unable to generate the RSS files.

Features says that rss is available.

**Comment by Vimux** [comment]
Mainroad use internal Hugo template for generating RSS.

Please describe more specifically what exactly does not work in RSS.

**Comment by vguhesan** [comment]
I'm not seeing any RSS files generated. At present, I run "hugo" to create/update the content on the /public folders. But no .rss files are being generated. Do I need to run a different command to generate the .rss files? Using "hugo server --theme=mainroad" for the live locahost webserver. I see a sitemap.xml file auto-generated but no RSS files.

**Comment by Vimux** [comment]
Internal Hugo RSS template generate index.xml files
