### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by PeterMeadows** [Vimux/Mainroad#4]
Hi,  I like your theme but have noticed that there seems to be a problem with the menu in recent days.  Also it would be good if the menu is responsive when viewed on a phone (like the MH Magazine Lite web site). Thanks.

**Comment by Vimux** [comment]
Hi, @PeterMeadows.

Could you give more useful information? Screenshot, screen resolution of your device, device type (mobile, tablet, laptop, desktop)?

From your description, I assume that the problem in demo. [Hugo themes site](http://themes.gohugo.io/) caching system (Cloudflare) works unpredictably. Some details can be found in open issues: [#186](https://github.com/spf13/hugoThemes/issues/186), [#200](https://github.com/spf13/hugoThemes/issues/200).

**Try my own alternative demo: [Mainroad](//hugothemes.gitlab.io/mainroad). It must work properly.**

**Comment by PeterMeadows** [comment]
Hi @Vimux,

You are correct that the problem lies with Hugo themes demo site.  Your alternative demo works perfectly. Thanks.  Happy New Year.

**Comment by Vimux** [comment]
> So I too am seeing issues with the exampleSite demo included with the theme and your alternative demo does render perfectly.

It's weird. Hugo Themes site cache problem was fixed a long time ago (in early 2017, probably).

Hugo themes site updated manually (once a week or so). Alternate demo updated automatically, used the same exampleSite with two [override config options](https://gohugo.io/getting-started/configuration/#configuration-file) and one (1) additional file as Theme Сomponent (`supportus.html` widget). My demo builds with minimum Hugo version (`0.43`) and the original minify package (`2.3.5`). That's all differences.

Alternate Demo config overrided options:

```
baseurl = "http://hugothemes.gitlab.io/mainroad/"

[Params.sidebar]
  widgets = ["search", "recent", "categories", "taglist", "supportus"]
```

Also see [#53](https://github.com/Vimux/Mainroad/issues/53#issuecomment-386236909).

> Being able to see the source to your working source demo above would be great.

https://github.com/Vimux/Mainroad/tree/master/exampleSite

---

If you have any troubles with Mainroad theme, please open a new issue with **SCREENSHOTS AND DETAILED INFORMATION** (hugo version, monitor resolution, DPI, other useful data).
