### ISSUE TITLE
Add math render suggestion

### ISSUE THREAD

**Issue by pennbay** [Vimux/Mainroad#40]
Mainly, there are two ways to add math render, 
1. [hugo official doc](https://gohugo.io/content-management/formats/#mmark), a specific demo can be find in [this blog](https://divadnojnarg.github.io/blog/mathjax/);
2. [Better TeX math typesetting in Hugo](http://www.latkin.org/blog/2016/08/07/better-tex-math-typesetting-in-hugo/), this method can reduce unnecessary  load of CDNs.

I think we can take advantages of both ways. I attempt to add this feature. How do you think about the two ways? @Vimux

**Comment by Vimux** [comment]
I don't plan to add mathJax. See #39 for details.

If necessary, I can add links "how to enable mathjax" to the README.md
