### ISSUE TITLE
Content does not appear on Home

### ISSUE THREAD

**Issue by Raggaer** [Vimux/Mainroad#49]
I have some content inside  `content/posts` folder and I can access it directly, however, the template will always say:

> 
> You don't have any posts yet!
> 
> As posts are added in content/post folder, they'll appear here.

And no recent posts will appear on the sidebar

Thanks

**Comment by murraycolin** [comment]
I think there might be some confusion on `content/posts` and `content/post`. I think it will default to `content/post`. Can you see what happens if you rename the directory?

**Comment by Vimux** [comment]
I clarify text in "no posts" empty state. See 0dc6f7f. I hope this helps to reduce such issue.
