### ISSUE TITLE
Missing google analytics support

### ISSUE THREAD

**Issue by jimmydigital** [Vimux/Mainroad#5]
It looks like you only added support for the googleAnalytics metadata to an _internal template file... going by the commits.  This needs to be pulled into the public code. I noticed it when my google data dropped to zero after switching to this theme. 

https://github.com/Vimux/Mainroad/commit/8f72fe40c3885ceb4ec335940d74225407269c93

**Comment by Vimux** [comment]
_internal templates (Google Analytics, Disqus Comments, etc) are provided by Hugo. I just plugged them to Mainroad.

GA stats should work. **Please make sure that you have correctly entered your GA tracking ID code in config.toml.** Example from [Hugo documentation](https://gohugo.io/extras/analytics/):

```toml
googleAnalytics = "UA-123-45" # Enable Google Analytics by entering your tracking id
```

**Comment by jimmydigital** [comment]
Interesting... I built hugo from source to run on my osx machine so I have only the hugo binary.  I don't have the _internal directory... it was't part of the freshly initialized site.  Disqus comments are working though... and my analytics id is defined in the config.  Still digging around to see what I'm missing.

**Comment by jimmydigital** [comment]
Ok nevermind... I see how this works now. These templates aren't files on disk.. they are literally embedded in the go source and get compiled in to the hugo binary.  It wasn't working because I had the googleAnalytics value set below the [permalinks] section in the config.

**Comment by maximouche** [comment]
adding it for the record.
The google analytics template is added on the condition 
```
        {{- if not .Site.IsServer }}
                {{ template "_internal/google_analytics_async.html" . }}
        {{- end }}
```
When built with gitlab-ci, the template is never added.

**Comment by Vimux** [comment]
First, https://github.com/Vimux/Mainroad/issues/5#issuecomment-612644460 is irrelevant to the original issue.

---

> When built with gitlab-ci, the template is never added.

`.Site.IsServer` - a boolean to indicate if the site is being served with Hugo’s built-in server.
So, if you set up your site correctly, this part should work as intended.

REF: https://gohugo.io/variables/site/#site-variables-list
