### ISSUE TITLE
Two issues: italics, mathjax

### ISSUE THREAD

**Issue by amca01** [Vimux/Mainroad#51]
I am experimenting with mainroad, whose look I like very much.  I currently have two issues:

1. Italics, such as `_italics_` in the markdown file, are not rendered in the final html.   How can I fix this?
1. I can't get mathjax to work.  I have a `mathjax.html` file which I have used with other themes, and which I have copied to the `layouts/partials` directory.  And I have included the line 

       {{  partial "mathjax.html" . }}

in `header.html` in that directory.  In other words, following the instructions [here](https://pennbay.github.io/tech/mathjax.with.hugo/).  As I say I have got mathjax working with other themes, but I can't seem to get it working with mainroad.

Almost every time I make a change, I remove the `public` directory, run `hugo` and then `hugo server` to see the results.  This ensures there are no left over files from previous edits.

Anyway, any help or advice would be very welcome!

**Comment by Vimux** [comment]
@amca01, I carefully checked the instruction.

In my case everything works after fixing typo (`mathjax : ture` -> `mathjax: true`):

![Mathjax in Hugo Mainroad theme](https://user-images.githubusercontent.com/21033483/39351250-949d3326-4a09-11e8-938a-5bef862ff730.png)

**Short guide:**
1. Place `mathjax.html` in `mainroad/layout/partials/`
2. Add `{{ if .Params.mathjax }}{{ partial "mathjax.html" . }}{{ end }}` in `footer.html` right before `</body>` tag:

```html
...
{{ if .Params.mathjax }}{{ partial "mathjax.html" . }}{{ end }}
</body>
</html>
```

3. Add `mathjax: true` parameter in post frontmatter:

```
---
title: MathJax
date: 2018-04-27
mathjax: true
---
```
