### ISSUE TITLE
Multilingual links

### ISSUE THREAD

**Issue by pennbay** [Vimux/Mainroad#55]
According to fbf98fcb10aeaa1c7365c0d90251d01c08620e52, multilingual string is added in `i18n/en.yaml`. I can added `fr.yaml` and `zh.ymal` to `i18n`. But there seems to be no multilingual links in pages. Could you please creat an example of multilingual links. @Vimux

**Comment by oshliaer** [comment]
@pennbay you have to setup to your config the next parameter
```toml
defaultContentLanguage = "fr"
```
