### ISSUE TITLE
URLs/pre/code from posts on frontpage not shown as expected

### ISSUE THREAD

**Issue by linuxmail** [Vimux/Mainroad#56]
hi,

thanks for your work and I realy like it :-) I'm moving from Wordpress and asking me, what I have done wrong, that code / pre / urls parts are normal text in the posts on the front page, but looks as expected if I click on the "full" text.

https://www.denny-fuchs.de/
<img width="703" alt="bildschirmfoto 2018-05-16 um 08 19 07" src="https://user-images.githubusercontent.com/1276233/40099804-df8da712-58e1-11e8-8690-f0a704b048a1.png">

**Comment by Vimux** [comment]
@linuxmail,

This is default Hugo behaviour for `{{ .Summary }}`. If you want to keep the formatting you have to manually insert the split (`<!--more-->`) after the summary.

For example: **[basic-elements.md](https://raw.githubusercontent.com/Vimux/Mainroad/master/exampleSite/content/post/basic-elements.md)**

**Comment by linuxmail** [comment]
Hello @Vimux ,

thanks a lot ! I've found many posts round about the Summary, but in the end, it isn't a good way to strip of any styles.
I have often posts, with only a short command or a link and than it looks awfull :-) It seems, there is no real way at the moment, to have a summary, but keep the style.

cu denny

ps. Do you have an Amazon whishlist or something else ?

**Comment by Vimux** [comment]
Hello @linuxmail,

> It seems, there is no real way at the moment, to have a summary, but keep the style.

Unfortunately, you are absolutely right!

> ps. Do you have an Amazon whishlist or something else?

No, thank you.
