### ISSUE TITLE
Front matter formating wrong on some example pages ?

### ISSUE THREAD

**Issue by LoneWorg** [Vimux/Mainroad#6]
Hi there, 

1st of, thanks for the porting of this nice theme to Hugo. I'm all new to this so I may be wrong, but I think you have some of the front matter headers that are not correct in the example files you provided. 

Example in "./mainroad/exampleSite/content/post/creating-a-new-theme.md" file you have : 

> ---
> author: "Michael Henderson"
> date: 2014-09-28
> linktitle: Creating a New Theme
> menu:
>   main:
>     parent: tutorials
> next: /tutorials/github-pages-blog
> prev: /tutorials/automated-deployments
> title: Creating a New Theme
> weight: 10
> ---

So on my own site I'm currently building, I took the example to build the menu and had errors with that. 
I think the expected separator in there is "=" and not ":" with double quotes on the variables (else I had problems launching the Hugo server, with an 'unexpected token' as stated by Hugo).

Keep up the good job ;).

edit : my bad, thought only the toml format was supported - will perform a bit more checking see what was going on with my template.

**Comment by Vimux** [comment]
Hi, @LoneWorg,

New menu doesn't support submenu yet. So, last menu item "tutorials" doesn't work properly.

`creating-a-new-theme.md` file creates an menu item "tutorials" with two active submenu items "Creating a New Theme" and "Migrating from Jekyll".

I will change `creating-a-new-theme.md` soon.

**Comment by LoneWorg** [comment]
All right, thanks for the feedback!
