### ISSUE TITLE
[class*="col-"] matches too much

### ISSUE THREAD

**Issue by edemaine** [Vimux/Mainroad#60]
This theme has two rules matching attributes `[class*="col-"]`.  This conflicts with (also matches) [KaTeX](https://khan.github.io/KaTeX/)'s [.col-align-* class definitions](https://github.com/Khan/KaTeX/blob/master/src/katex.less#L424-L434).  This was encountered by a real user: https://github.com/Khan/KaTeX/issues/1445#issuecomment-401242459

The trouble is that, even if KaTeX isolates its class definitions as e.g. `.katex-col-align-*`, we would still have a conflict.  Is there a stricter matching rule that you can use?  I'm one of the KaTeX maintainers and can submit a PR on our side, but I'd rather not have to avoid any class name containing `col-` as a substring...

**Comment by Vimux** [comment]
Hi, @edemaine 

I understand the problem.

Honestly, it's a weird CSS from our side. We inherited CSS from MH Magazine lite. Accidentally, in some refactoring stage, I "broke" this code section. Now, Mainroad doesn't use `col-*` rules at all. So I'll just delete this piece of code.

Thank you for report.
