### ISSUE TITLE
CSS styling not carrying over into /public

### ISSUE THREAD

**Issue by phmullins** [Vimux/Mainroad#7]
Hello. 

Does anyone have a clue why the CSS styling doesn't carry over in the `/public` folder? Everything works fine when previewing with Hugo's built-in web server. However, moving the contents of `/public` to my web server results in all text and no CSS. I've tried everything that I can think of and I can't figure out what's causing it. 

Patrick

**Comment by LoneWorg** [comment]
Hi there, 

Check your **baseurl** parameter into your **config.toml file**. Usually when we check the preview this is using "localhost" or "/", and we may forget to put our live url into that param when deploying in production.  This the issue I had when the css was not working (as paths were messed up).

**Comment by phmullins** [comment]
Thank you, LoneWorg! I had messed up the **baseurl**. Everything is working fine now. :-)
