### ISSUE TITLE
Add Gitlab social widget.

### ISSUE THREAD

**Issue by boweevil** [Vimux/Mainroad#70]
I'm prepared to submit a PR for this.  I've used the icon from https://commons.wikimedia.org/wiki/File:Gitlab_font_awesome.svg.  Would that be ok?

![image](https://user-images.githubusercontent.com/16481398/44619235-25839d80-a851-11e8-9a2c-13172ec65e70.png)

**Comment by Vimux** [comment]
At first glance, everything is fine.

Pay attention:

1) Need to optimize SVG
2) What about license? What do we need to do?
3) Look at #67 social.html

**Comment by boweevil** [comment]
Sounds good.  I'm not sure how to optimize SVGs as this is my first time messing with them in HTML.  Can you point me to a good explaination or tutorial?  Meanwhile, I will research this subject.  I'll check on the licensing as well.  Would it make sense to submit my PR to pkel to make it part of his PR?

**Comment by Vimux** [comment]
1) Just use [SVGO](https://github.com/svg/svgo). That's enough for now.
2) OK, good.
3) No, it's an example. Main point for you:

`{{- with .Site.Params.widgets.social_gitlab }}` -> `{{- with .Site.Params.widgets.social.gitlab }}`

**Comment by boweevil** [comment]
For licensing it is under the [SIL Open Font License](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web).  It is also part of Font Awesome.  It says the the "font software" would need to be distributed under that license.  From where did the Github icon come?  Purhaps there is a Gitlab icon which can be distributed under the GPL?

**Comment by Vimux** [comment]
Take a look at  [https://github.com/gilbarbara/logos/blob/master/logos/gitlab.svg](https://github.com/gilbarbara/logos/blob/master/logos/gitlab.svg) [CC0-1.0]

**Comment by boweevil** [comment]
OK that works for me.  I've modified the image from the link you gave me to be monochrome and have the following result.
![image](https://user-images.githubusercontent.com/16481398/44658138-a49de080-a9cd-11e8-8d73-32fbaa9b53cb.png)
