### ISSUE TITLE
Content on list pages is not rendered well

### ISSUE THREAD

**Issue by pkel** [Vimux/Mainroad#77]
Content on pages using the list template is not rendered well. [This test case](https://github.com/pkel/Mainroad/blob/list-css/exampleSite/content/post/_index.md) highlights the problem.

![brokenlist](https://user-images.githubusercontent.com/11337857/44751041-63194c80-ab17-11e8-996b-50d06c16faf9.png)

I think the correct approach to solving this is moving the css properties for children of `post__content` to `content`. Then overwrite for children of `meta`, `list__item` and so forth. What do you think?

**Comment by Vimux** [comment]
I created a new branch `fix-site-layout` with a more reliable solution. After several tests, I plan to add changes to the master branch. If you find a bug, please report it to me.
