### ISSUE TITLE
Added some stuff, can check on loneworg.com 

### ISSUE THREAD

**Issue by LoneWorg** [Vimux/Mainroad#8]
Hi Vimux, 

Not sure how the pulling requesting works yet (need to read a bit more about GIT), but just so you know I did a few changes on the template that you can see on my live address here : http://loneworg.com 

Stuff added for now (not taking images added into account as this is trivial and a matter of personal taste) :  
- "Read more" button  (changed in list.html + style.css)

Next on the list  : 
- Better image embedded management (pop-in)

Let me know if interested to put that in your mainstream

**Comment by Vimux** [comment]
Hi @LoneWorg,

 I'm sorry for the long delay.

I checked site. Current state of "read more" buttons needs to be improved:

1. No padding between button and text
2. Unusual design and hover behavior (as compared with tags widget)
3. BEM-like class naming (I recently changed the way of naming classes)

You also need to add ability to turn on/off read more buttons via config.toml (default value — off).

Let me know if you have a desire to correct these items.

P.S. Why not just take design from tags widget?

![read_more](https://cloud.githubusercontent.com/assets/21033483/22083787/917f1bac-ddde-11e6-98a3-704f300311c0.png)
