### ISSUE TITLE
Theme requires safeHTML ?

### ISSUE THREAD

**Issue by stefkes** [Vimux/Mainroad#81]
When my frontmatter title contains a colon character I have to use the entity `&#58;` because using a normal colon breaks the YAML syntax

YAML:

```
---
title: Test&#58; post
date: 2019/01/01
---
```

This entity isn't "rendered" on the generated page unless I make the following changes:

In `single.html`
`<h1 class="post__title">{{ .Title }}</h1>`
should be
`<h1 class="post__title">{{ .Title | safeHTML}}</h1>`

and in `summary.html`
`<a href="{{ .RelPermalink }}" rel="bookmark">{{ .Title }}</a>`
should be
`<a href="{{ .RelPermalink }}" rel="bookmark">{{ .Title | safeHTML }}</a>`

Is this a bug of sorts or am I missing something?

**Comment by Vimux** [comment]
```yml
---
title: "Test: example post"
---
```

**Comment by stefkes** [comment]
Thanks for your quick reply. What is best practise in case of:

```
---
title: "Test: "example" post"
---
```

?

**Comment by Vimux** [comment]
```yml
---
title: "Test: \"example\" post"
---
```

[Escape character](https://en.wikipedia.org/wiki/Escape_character#Programming_and_data_formats)
