### ISSUE TITLE
mathjax is not enabled on main page

### ISSUE THREAD

**Issue by belger-dussen** [Vimux/Mainroad#82]
Even enabling mathjax option, it will not render math formula on the main page. I think it will be better to add, 
{{- partial "mathjax.html" . -}}
at summary.html as well.

**Comment by Vimux** [comment]
> I think it will be better to add, {{- partial "mathjax.html" . -}} at summary.html as well.

No. I'm not going to change it.

**Comment by pkel** [comment]
What happens if you add `mathjax: true` to the frontmatter of `content/_index.md`?
