### ISSUE TITLE
Proposal of categories arrangement

### ISSUE THREAD

**Issue by magicstone1412** [Vimux/Mainroad#84]
I am not a programmer and a newbie to Hugo. I am using your theme. And can I ask for your help with the theme improvements?
As the title says, I would like to propose the following items about categories,
1. could you please add categories to config.toml file and under the categories section in theme, it only shows the categories added in config.toml file?
2. could you please make categories order arrangeable? For example, the categories order can be got from the config.toml file.
3. I would like to get your help to put the categories in the config.toml to the horizontal navigation bar.

Thank you so much for your them. I hope my proposal will be accepted.

**Comment by Vimux** [comment]
1&2: You can use a secondary menu and add categories manually. See [Hugo Menus](https://gohugo.io/content-management/menus/#advanced) for more info about menu items ordering.

3: No. The same as #78.
