### ISSUE TITLE
Add a submenu

### ISSUE THREAD

**Issue by luoshuitaotao** [Vimux/Mainroad#86]
Hi, thank you very much for your nice work. It is a very good theme.

I was wondering if it was possible to use submenus ? I was wondering to add a submenu which is similar as HTML Dropdown Menu. 

Thank you so much. Really appreciated.

**Comment by pkel** [comment]
You might be interested in #85. It is not exactly what you propose, but helps to fit more links into the page.

**Comment by luoshuitaotao** [comment]
Thank you so much. I really appreciated.

**Comment by Vimux** [comment]
> I was wondering if it was possible to use submenus?

No, Mainroad main menu doesn't support submenus.

**Comment by ashishlahoti** [comment]
Thanks. I understand that it is not supported at the moment. However, I've implemented the responsive nested menu structure on my own on top of hugo mainroad theme, which might be helpful for others:

https://codingnconcepts.com/hugo/nested-menu-hugo/
