### ISSUE TITLE
SEO  mobile usability errors

### ISSUE THREAD

**Issue by magicstone1412** [Vimux/Mainroad#89]
I got 2 errors in https://search.google.com/search-console/mobile-usability when using the theme as below

1.  "Clickable elements too close together"
2. "Content wider than screen"

But when I checked the site on my phone. It's okay. Maybe the errors came from CSS ( I guess). Could  you please check and fix it? Thank you

![Search Console Errors](https://i.imgur.com/9fiSoFw.png "Search Console Errors")

**Comment by Vimux** [comment]
Could you provide more information? Site URL with errors? Specific page with errors? More specific information from Google Search Console?

**Comment by magicstone1412** [comment]
This site
https://search.google.com/search-console/mobile-usability?resource_id=https%3A%2F%2Fwww.onlinekiem.com%2F

Many urls have errors please see the attach photo
![Erros urls](https://i.imgur.com/V4rZWBz.png)

More information about this matter I found on the internet
https://github.com/pstephens/kingjames.bible/issues/26

Thank you for paying your attention to this problem

**Comment by Vimux** [comment]
You use highly customizable Mainroad theme. I can not say for sure, probably your modifications could lead to such an effect. I need confirmation using the original theme, not modified.

**This issue tracker is about features and bugs in the original version of the Mainroad, not all its possible forks.**

**Comment by magicstone1412** [comment]
I don't touch so much to the theme. I just changed the color. You can check with the other people using this theme. Thank you. And please pay attention to the link above

**Comment by Vimux** [comment]
> I don't touch so much to the theme. I just changed the color. 

Really? Well, I open your GitHub profile, open your Github Pages repo [magicstone1412/magicstone1412.github.io](https://github.com/magicstone1412/magicstone1412.github.io) and see some changes in the last commit [magicstone1412/magicstone1412.github.io@8e87d11](https://github.com/magicstone1412/magicstone1412.github.io/commit/8e87d1198178f5bb1f5faa0fcc82005569574244). Looks like someone deleted theme credits ("Generated with Hugo and Mainroad theme") for all pages in footer earlier and then restore it. So, you changed the color only, right? OK, nevermind.

---

Your link contains link to Google Mobile-Friendly Test.  Have you tested your site with [Google Mobile-Friendly Test](https://search.google.com/test/mobile-friendly)? I quickly tested.

Your site check:
https://search.google.com/test/mobile-friendly?id=Win0FLP8nxinQ-2z8xZnTw [FAIL]

Official Mainroad demo check:
https://search.google.com/test/mobile-friendly?id=X0diLQc0YSruOEZC6CWpeA [PASSED]

Looks like bloatware (maybe heavy JS bundle) or something else slow down your pages.

**I repeat this issue tracker is about features and bugs in the original version of the Mainroad. End of discussion.**

**Comment by magicstone1412** [comment]
I think I need to restore that line before giving you the link. Sorry if you feel NOT free with that.

As far as I think, the information of credit is always including in the meta.
