### ISSUE TITLE
Detect translations for lists

### ISSUE THREAD

**Issue by oshliaer** [Vimux/Mainroad#93]
Is there the best way to translate [site_url/tags/](https://hugothemes.gitlab.io/mainroad/tags/) and [site_url/categories/](https://hugothemes.gitlab.io/mainroad/categories/) list pages?

In the current state I have to do something like this 

```html
{{ define "main" }}
<main class="main list" role="main">
	{{ $type := .Type }}
	{{- with .Title }}
	<header class="main__header">
		<h1 class="main__title">
			{{ if in (slice "tags" "categories") $type }} 
				{{ T ( print $type "_title" ) }}
			{{ else }}
				{{ . }}
			{{ end }}
		</h1>
	</header>
	{{- end }}
	{{- with .Content }}
	<div class="content main__content clearfix">
		{{ . }}
	</div>
	{{- end }}
	{{- range .Paginator.Pages }}
		{{- .Render "summary" }}
	{{- end }}
</main>
{{ partial "pagination.html" . }}
{{ end }}
```

**Comment by Vimux** [comment]
I can't come up with a better solution. Maybe you should try asking a question on [discourse.gohugo.io](https://discourse.gohugo.io/)?

**Comment by oshliaer** [comment]
@Vimux , thanks.

Let me close this here now.
