### ISSUE TITLE
Add Instagram to social widgets

### ISSUE THREAD

**Issue by RSteenson** [Vimux/Mainroad#94]
Hi, 
I've been trying to figure out how to add to the social widgets myself, but I'm new to Blogdown and unsure which file to use!
Can you please add Instagram to the list of available social widgets?

Rachel

**Comment by Vimux** [comment]
Hi!

Thank you for your request. I don’t have time to add Instagram in social widget right now, but I accept such PRs. Maybe someone is interested in this and will create a PR? #71 & #83 may serve as an example.
