### ISSUE TITLE
Handling of non 16px fontsize in browser

### ISSUE THREAD

**Issue by pkel** [Vimux/Mainroad#96]
When I change the default fontsize from 16px to 14px or 10px, I see the following (on Firefox).

![fs10](https://user-images.githubusercontent.com/11337857/47114545-6f3ea200-d25c-11e8-99df-c319bb2ae87c.png)
![fs14](https://user-images.githubusercontent.com/11337857/47114564-75cd1980-d25c-11e8-84ef-7ae1ea99c19a.png)
![fs16](https://user-images.githubusercontent.com/11337857/47114569-7960a080-d25c-11e8-8fbb-cf8de6f929b6.png)

**Comment by Vimux** [comment]
Yep, it's a bug.

I plan to add a new menu without third-party dependencies (just a little pure JS + CSS). I need to do a few checks before pushing it. This problem will be solved by switching to a new menu.

**Comment by Vimux** [comment]
@pkel, please check #99. Is it all right now?

**Comment by pkel** [comment]
#99 seems to solve the issue on my Firefox. Nice!

**Comment by Vimux** [comment]
Good. I need to do additional check (IE and others) before merge.
